# Awesome List Generator Configuration
# This file configures your self-hosted awesome list site

# Site Configuration
site:
  title: "Awesome Self-Hosted"
  description: "A list of Free Software network services and web applications which can be hosted on your own servers"
  url: "https://awesome-selfhosted.net"
  author: "awesome-selfhosted community"
  
# Source Configuration
source:
  # Primary awesome list to parse
  url: "https://raw.githubusercontent.com/awesome-selfhosted/awesome-selfhosted/master/README.md"
  # Auto-refresh interval in minutes (0 to disable)
  refresh_interval: 60
  # Additional lists for multi-list switching
  additional_lists:
    - name: "Awesome Go"
      url: "https://raw.githubusercontent.com/avelino/awesome-go/main/README.md"
      category: "Programming"
      icon: "🐹"
    - name: "Awesome Python"
      url: "https://raw.githubusercontent.com/vinta/awesome-python/master/README.md"
      category: "Programming"
      icon: "🐍"
    - name: "Awesome JavaScript"
      url: "https://raw.githubusercontent.com/sorrycc/awesome-javascript/master/README.md"
      category: "Programming"
      icon: "💛"

# Theme Configuration
theme:
  # Default theme: light, dark, or auto
  default: "auto"
  # Primary color scheme
  primary_color: "#dc2626" # Dark red
  # Custom themes
  custom_themes:
    - name: "Ocean"
      primary: "#0ea5e9"
      secondary: "#0284c7"
      background: "#f8fafc"
    - name: "Forest"
      primary: "#059669"
      secondary: "#047857"
      background: "#f0fdf4"

# Analytics Configuration
analytics:
  # Google Analytics 4 Measurement ID
  google_analytics: "${VITE_GA_MEASUREMENT_ID}"
  # Track these events
  events:
    - resource_clicks
    - category_views
    - search_queries
    - theme_changes
    - list_switches
  # Privacy settings
  anonymize_ip: true
  cookie_consent: true

# Features Configuration
features:
  # Enable/disable specific features
  search: true
  categories: true
  analytics_dashboard: true
  theme_switcher: true
  list_switcher: true
  resource_previews: true
  # Pagination settings
  pagination: true
  items_per_page: 24
  page_size_options: [12, 24, 48, 96]
  # AI-powered features (requires OpenAI API key)
  ai_tags: false
  ai_descriptions: false

# Build Configuration
build:
  # Output directory for static builds
  output_dir: "dist"
  # Base URL for static deployment
  base_url: "/"
  # Generate sitemap
  sitemap: true
  # Generate RSS feed
  rss_feed: true

# Deployment Configuration
deploy:
  # Deployment method: github-pages, vercel, netlify, manual
  method: "github-pages"
  # Custom domain (optional)
  custom_domain: ""
  # GitHub Pages specific settings
  github:
    repository: "username/awesome-list-site"
    branch: "gh-pages"
    cname: ""

# SEO Configuration
seo:
  # Meta tags
  keywords: "awesome, curated, list, self-hosted, open-source"
  # Open Graph settings
  og_image: "https://awesome-selfhosted.net/og-image.png"
  # Twitter Card settings
  twitter_card: "summary_large_image"
  twitter_site: "@awesome_sh"

# Performance Configuration
performance:
  # Enable service worker for offline support
  service_worker: true
  # Cache duration in seconds
  cache_duration: 3600
  # Lazy load images
  lazy_loading: true