allowBuilds:
  '@scarf/scarf': set this to true or false
  bufferutil: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
  puppeteer: set this to true or false
  sharp: set this to true or false
