#!/usr/bin/env bash
# Generate the project .env used by the Cloud Agent dev environment.
#
# Values already present in the process environment (e.g. Cursor secrets such as
# real Clerk keys or an external DATABASE_URL) always win; anything unset falls
# back to a local-development default so the app can boot for public browsing
# without external accounts. Clerk placeholders are syntactically valid
# development keys — they let ClerkProvider initialize and the public catalog
# render, but real sign-in/admin flows require real Clerk keys supplied as
# secrets.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# A well-formed but non-functional Clerk *development* publishable key
# (base64 of "sterling-mongoose-42.clerk.accounts.dev$"). Parses cleanly via
# @clerk/shared so the client bundle boots; it authenticates against nothing.
PLACEHOLDER_CLERK_PK="pk_test_c3RlcmxpbmctbW9uZ29vc2UtNDIuY2xlcmsuYWNjb3VudHMuZGV2JA=="
PLACEHOLDER_CLERK_SK="sk_test_placeholderplaceholderplaceholder00"

DATABASE_URL_VALUE="${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/awesome_list}"
CLERK_PUBLISHABLE_KEY_VALUE="${CLERK_PUBLISHABLE_KEY:-$PLACEHOLDER_CLERK_PK}"
CLERK_SECRET_KEY_VALUE="${CLERK_SECRET_KEY:-$PLACEHOLDER_CLERK_SK}"
VITE_CLERK_PUBLISHABLE_KEY_VALUE="${VITE_CLERK_PUBLISHABLE_KEY:-$CLERK_PUBLISHABLE_KEY_VALUE}"
VITE_CLERK_PROXY_URL_VALUE="${VITE_CLERK_PROXY_URL:-/api/__clerk}"
NODE_ENV_VALUE="${NODE_ENV:-development}"
PORT_VALUE="${PORT:-5000}"

cat > "$REPO_ROOT/.env" <<EOF
# Auto-generated by scripts/cloud-agent/write-env.sh — do not edit by hand.
# Real values injected as environment variables/secrets take precedence.
DATABASE_URL=$DATABASE_URL_VALUE
CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_VALUE
CLERK_SECRET_KEY=$CLERK_SECRET_KEY_VALUE
VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY_VALUE
VITE_CLERK_PROXY_URL=$VITE_CLERK_PROXY_URL_VALUE
NODE_ENV=$NODE_ENV_VALUE
PORT=$PORT_VALUE
EOF

echo "Wrote $REPO_ROOT/.env (DATABASE_URL host: $(echo "$DATABASE_URL_VALUE" | sed -E 's#.*@([^/]+).*#\1#'))"
