/**
 * Link Checker for Awesome Lists
 * Validates all URLs in resources similar to awesome_bot
 */

import fetch from 'node-fetch';
import * as tls from 'node:tls';
import * as https from 'node:https';
import * as http from 'node:http';
import * as net from 'node:net';
import { lookup as dnsLookup } from 'node:dns/promises';
import { X509Certificate } from 'node:crypto';

export interface LinkCheckResult {
  url: string;
  status: number;
  statusText: string;
  valid: boolean;
  redirectUrl?: string;
  /** URL after following all redirects */
  finalUrl?: string;
  /** Set when the destination returns 200 but heuristics say the content is gone (R4-001/023 class) */
  suspicion?: 'domain-takeover' | 'intent-flip-root' | 'parked-content';
  suspicionDetail?: string;
  responseTime: number;
  error?: string;
  resourceTitle?: string;
  resourceId?: number;
}

export interface LinkCheckReport {
  totalLinks: number;
  validLinks: number;
  brokenLinks: number;
  redirects: number;
  errors: number;
  results: LinkCheckResult[];
  summary: {
    byStatus: { [status: string]: number };
    averageResponseTime: number;
  };
  timestamp: string;
}

export interface LinkCheckOptions {
  timeout?: number; // Default 10 seconds
  followRedirects?: boolean; // Default true
  userAgent?: string;
  concurrent?: number; // Number of concurrent checks, default 5
  retryCount?: number; // Number of retries for failed checks, default 1
  // R5-008 (run24): incremental progress hook — called after every completed
  // batch with the running checked count so long sweeps can report progress
  // instead of sitting at 0 until the final commit.
  onProgress?: (checked: number, total: number) => void;
}

/**
 * "Domain-takeover / intent-flip at 200" heuristics (R4-001/R4-023 class):
 * a 200 response is NOT proof the referenced content still exists. Three
 * failure shapes the plain status check misses:
 *  1. domain-takeover: the registrable domain changed via redirect
 *     (kurento.org -> twilio.com marketing).
 *  2. intent-flip-root: a deep link now lands on the site root — vendor
 *     restructures kill the article but 301 to "/" (drift-to-root cluster).
 *  3. parked-content: same-domain 200 serving a domain-parking/spam page
 *     (afterglowplayer.com gambling spam, GoDaddy lander).
 */

/** Registrable-domain approximation (handles common two-part public suffixes). */
const TWO_PART_TLDS = new Set([
  'co.uk', 'org.uk', 'ac.uk', 'gov.uk', 'com.au', 'net.au', 'org.au',
  'co.jp', 'or.jp', 'ne.jp', 'com.br', 'com.cn', 'com.tw', 'co.in',
  'co.nz', 'co.kr', 'com.mx', 'com.sg', 'co.za', 'com.hk',
]);

export function registrableDomain(hostname: string): string {
  const parts = hostname.toLowerCase().replace(/\.$/, '').split('.');
  if (parts.length <= 2) return parts.join('.');
  const lastTwo = parts.slice(-2).join('.');
  if (TWO_PART_TLDS.has(lastTwo)) return parts.slice(-3).join('.');
  return lastTwo;
}

/** Registrable-domain pairs that are the same property (never a takeover). */
const EQUIVALENT_DOMAINS: Array<[string, string]> = [
  ['youtu.be', 'youtube.com'],
  ['goo.gl', 'google.com'],
  ['aka.ms', 'microsoft.com'],
  ['fb.me', 'facebook.com'],
  ['t.co', 'twitter.com'],
  ['twitter.com', 'x.com'],
];

function domainsEquivalent(a: string, b: string): boolean {
  if (a === b) return true;
  return EQUIVALENT_DOMAINS.some(([x, y]) => (a === x && b === y) || (a === y && b === x));
}

/** Conservative parked/for-sale phrases — any hit in the body start is a lander. */
const PARKED_PHRASES = [
  'domain is for sale', 'this domain is for sale', 'buy this domain',
  'domain has expired', 'domain name expired', 'parked free', 'domain parking',
  'sedoparking', 'parking-lander', 'parkingcrew', 'hugedomains', 'afternic',
  'this webpage was generated by the domain owner', 'get this domain',
  'the domain owner is offering it for sale', 'related searches',
];

/** Spam-takeover signals — matched in the <title> only to avoid false positives. */
const SPAM_TITLE_TERMS = [
  'casino', 'slot gacor', 'slot online', 'togel', 'judi ', 'poker online', 'betting site',
];

export function detectParkedContent(bodyStart: string): string | null {
  const lower = bodyStart.toLowerCase();
  for (const phrase of PARKED_PHRASES) {
    if (lower.includes(phrase)) return `parked-domain phrase: "${phrase}"`;
  }
  const titleMatch = lower.match(/<title[^>]*>([\s\S]{0,300}?)<\/title>/);
  if (titleMatch) {
    for (const term of SPAM_TITLE_TERMS) {
      if (titleMatch[1].includes(term)) return `spam takeover title term: "${term.trim()}"`;
    }
  }
  return null;
}

export function evaluateRedirectSuspicion(
  originalUrl: string,
  finalUrl: string | undefined,
): Pick<LinkCheckResult, 'suspicion' | 'suspicionDetail'> {
  if (!finalUrl || finalUrl === originalUrl) return {};
  try {
    const orig = new URL(originalUrl);
    const fin = new URL(finalUrl);
    const origDomain = registrableDomain(orig.hostname);
    const finDomain = registrableDomain(fin.hostname);
    if (!domainsEquivalent(origDomain, finDomain)) {
      return {
        suspicion: 'domain-takeover',
        suspicionDetail: `redirects off-domain: ${origDomain} -> ${finDomain} (${finalUrl})`,
      };
    }
    const origPath = orig.pathname.replace(/\/+$/, '');
    const finPath = fin.pathname.replace(/\/+$/, '');
    // Deep link collapsed to the site root => the referenced content is gone.
    if (origPath.length > 1 && finPath === '' && !fin.search && !fin.hash) {
      return {
        suspicion: 'intent-flip-root',
        suspicionDetail: `deep link collapsed to site root: ${orig.pathname} -> /`,
      };
    }
  } catch {
    /* unparseable URLs: no suspicion */
  }
  return {};
}

export class LinkChecker {
  private options: Required<Omit<LinkCheckOptions, 'onProgress'>>;
  // R5-008: optional incremental-progress callback (not part of the Required
  // options bag — it has no sensible default).
  private onProgress?: (checked: number, total: number) => void;

  constructor(options: LinkCheckOptions = {}) {
    this.options = {
      timeout: options.timeout || 10000,
      followRedirects: options.followRedirects !== false,
      userAgent: options.userAgent || 'Mozilla/5.0 (compatible; AwesomeListBot/1.0)',
      concurrent: options.concurrent || 5,
      retryCount: options.retryCount || 1
    };
    this.onProgress = options.onProgress;
  }

  /**
   * Check all links in the provided resources
   */
  async checkLinks(links: Array<{ url: string; title?: string; id?: number }>): Promise<LinkCheckReport> {
    const startTime = Date.now();
    const results: LinkCheckResult[] = [];
    
    // Process links in batches for concurrent checking
    const batches = this.createBatches(links, this.options.concurrent);
    
    for (const batch of batches) {
      const batchResults = await Promise.all(
        batch.map(link => this.checkSingleLink(link))
      );
      results.push(...batchResults);
      // R5-008: surface incremental progress after each batch.
      this.onProgress?.(results.length, links.length);
    }

    // Calculate statistics
    const validLinks = results.filter(r => r.valid).length;
    const brokenLinks = results.filter(r => !r.valid && r.status >= 400).length;
    const redirects = results.filter(r => r.status >= 300 && r.status < 400).length;
    const errors = results.filter(r => r.error).length;
    
    const byStatus: { [status: string]: number } = {};
    results.forEach(r => {
      const statusGroup = r.status ? `${Math.floor(r.status / 100)}xx` : 'error';
      byStatus[statusGroup] = (byStatus[statusGroup] || 0) + 1;
    });

    const totalResponseTime = results.reduce((sum, r) => sum + r.responseTime, 0);
    const averageResponseTime = results.length > 0 ? totalResponseTime / results.length : 0;

    return {
      totalLinks: links.length,
      validLinks,
      brokenLinks,
      redirects,
      errors,
      results,
      summary: {
        byStatus,
        averageResponseTime
      },
      timestamp: new Date().toISOString()
    };
  }

  /**
   * Check a single link
   */
  private async checkSingleLink(link: { url: string; title?: string; id?: number }): Promise<LinkCheckResult> {
    let attempts = 0;
    let lastError: Error | undefined;
    let result: LinkCheckResult | undefined;

    while (attempts <= this.options.retryCount) {
      try {
        result = await this.performCheck(link);
        if (result.valid || result.status < 500) {
          // Don't retry client errors (4xx) or successful responses
          break;
        }
      } catch (error) {
        lastError = error as Error;
      }
      attempts++;
      
      // Wait before retry (exponential backoff)
      if (attempts <= this.options.retryCount) {
        await this.sleep(Math.pow(2, attempts) * 1000);
      }
    }

    if (!result) {
      return {
        url: link.url,
        status: 0,
        statusText: 'Connection Failed',
        valid: false,
        responseTime: 0,
        error: lastError?.message || 'Unknown error',
        resourceTitle: link.title,
        resourceId: link.id
      };
    }

    return result;
  }

  /**
   * Perform the actual HTTP check
   */
  private async performCheck(link: { url: string; title?: string; id?: number }): Promise<LinkCheckResult> {
    const startTime = Date.now();
    
    try {
      // Skip non-HTTP URLs
      if (!link.url.startsWith('http://') && !link.url.startsWith('https://')) {
        return {
          url: link.url,
          status: 0,
          statusText: 'Non-HTTP URL',
          valid: true, // Consider non-HTTP URLs as valid (e.g., mailto:, ftp:)
          responseTime: 0,
          resourceTitle: link.title,
          resourceId: link.id
        };
      }

      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), this.options.timeout);

      try {
        const response = await fetch(link.url, {
          method: 'HEAD', // Use HEAD to avoid downloading content
          signal: controller.signal,
          headers: {
            'User-Agent': this.options.userAgent,
            'Accept': '*/*'
          },
          redirect: this.options.followRedirects ? 'follow' : 'manual'
        });

        clearTimeout(timeout);

        // Check for redirects
        let redirectUrl: string | undefined;
        if (response.status >= 300 && response.status < 400) {
          redirectUrl = response.headers.get('location') || undefined;
        }

        const valid = response.status >= 200 && response.status < 400;
        const finalUrl = response.url || undefined;

        // Takeover / intent-flip heuristics: only meaningful on OK responses.
        let suspicion = valid ? evaluateRedirectSuspicion(link.url, finalUrl) : {};
        if (valid && !suspicion.suspicion && response.status === 200) {
          const contentType = response.headers.get('content-type') || '';
          if (contentType.includes('text/html')) {
            const parked = await this.scanBodyForParkedContent(finalUrl || link.url);
            if (parked) {
              suspicion = { suspicion: 'parked-content', suspicionDetail: parked };
            }
          }
        }

        const responseTime = Date.now() - startTime;

        return {
          url: link.url,
          status: response.status,
          statusText: response.statusText,
          valid,
          redirectUrl,
          finalUrl,
          ...suspicion,
          responseTime,
          resourceTitle: link.title,
          resourceId: link.id
        };
      } catch (fetchError: unknown) {
        clearTimeout(timeout);

        // If HEAD fails, try GET (some servers don't support HEAD)
        if (fetchError instanceof Error && fetchError.name !== 'AbortError') {
          const getResponse = await this.tryGetRequest(link.url, controller.signal);
          if (getResponse) {
            const responseTime = Date.now() - startTime;
            return {
              ...getResponse,
              responseTime,
              resourceTitle: link.title,
              resourceId: link.id
            };
          }
        }
        
        throw fetchError;
      }
    } catch (error: unknown) {
      const responseTime = Date.now() - startTime;

      // Handle specific error types
      let statusText = 'Connection Error';
      let errorMessage = 'Unknown error';

      if (error instanceof Error) {
        errorMessage = error.message;
        if (error.name === 'AbortError') {
          statusText = 'Timeout';
        }
      }

      // Check for Node.js error codes
      if (typeof error === 'object' && error !== null && 'code' in error) {
        const code = (error as { code?: string }).code;
        if (code === 'ENOTFOUND') {
          statusText = 'DNS Not Found';
        } else if (code === 'ECONNREFUSED') {
          statusText = 'Connection Refused';
        } else if (code === 'CERT_HAS_EXPIRED') {
          statusText = 'SSL Certificate Expired';
        }
      }

      return {
        url: link.url,
        status: 0,
        statusText,
        valid: false,
        responseTime,
        error: errorMessage,
        resourceTitle: link.title,
        resourceId: link.id
      };
    }
  }

  /**
   * Try a GET request if HEAD fails
   */
  private async tryGetRequest(url: string, signal: AbortSignal): Promise<Omit<LinkCheckResult, 'responseTime' | 'resourceTitle' | 'resourceId'> | null> {
    try {
      const response = await fetch(url, {
        method: 'GET',
        signal,
        headers: {
          'User-Agent': this.options.userAgent,
          'Accept': '*/*'
        },
        redirect: this.options.followRedirects ? 'follow' : 'manual'
      });

      const valid = response.status >= 200 && response.status < 400;
      let redirectUrl: string | undefined;
      
      if (response.status >= 300 && response.status < 400) {
        redirectUrl = response.headers.get('location') || undefined;
      }

      const finalUrl = response.url || undefined;
      let suspicion = valid ? evaluateRedirectSuspicion(url, finalUrl) : {};
      if (valid && !suspicion.suspicion && response.status === 200) {
        const contentType = response.headers.get('content-type') || '';
        if (contentType.includes('text/html')) {
          try {
            const bodyStart = (await response.text()).slice(0, 65536);
            const parked = detectParkedContent(bodyStart);
            if (parked) suspicion = { suspicion: 'parked-content', suspicionDetail: parked };
          } catch {
            /* body read failed: keep status-based verdict */
          }
        }
      }

      return {
        url,
        status: response.status,
        statusText: response.statusText,
        valid,
        redirectUrl,
        finalUrl,
        ...suspicion
      };
    } catch {
      return null;
    }
  }

  /**
   * Fetch the first ~64KB of an HTML page and scan for parked/takeover
   * signatures. Failures are treated as "no suspicion" — this heuristic must
   * never turn a healthy link into a broken one on network noise.
   */
  private async scanBodyForParkedContent(url: string): Promise<string | null> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), Math.min(this.options.timeout, 10000));
    try {
      const response = await fetch(url, {
        method: 'GET',
        signal: controller.signal,
        headers: {
          'User-Agent': this.options.userAgent,
          'Accept': 'text/html',
          'Range': 'bytes=0-65535'
        },
        redirect: 'follow',
        size: 262144 // hard cap: never buffer more than 256KB
      });
      if (!response.ok && response.status !== 206) return null;
      const bodyStart = (await response.text()).slice(0, 65536);
      return detectParkedContent(bodyStart);
    } catch {
      return null;
    } finally {
      clearTimeout(timeout);
    }
  }

  /**
   * Create batches for concurrent processing
   */
  private createBatches<T>(items: T[], batchSize: number): T[][] {
    const batches: T[][] = [];
    for (let i = 0; i < items.length; i += batchSize) {
      batches.push(items.slice(i, i + batchSize));
    }
    return batches;
  }

  /**
   * Sleep for the specified milliseconds
   */
  private sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}

/**
 * Format link check report as markdown
 */
export function formatLinkCheckReport(report: LinkCheckReport): string {
  const lines: string[] = [];
  
  lines.push('# Link Check Report');
  lines.push('');
  lines.push(`Generated: ${new Date(report.timestamp).toLocaleString()}`);
  lines.push('');
  
  lines.push('## Summary');
  lines.push(`- Total Links: ${report.totalLinks}`);
  lines.push(`- ✅ Valid Links: ${report.validLinks} (${((report.validLinks / report.totalLinks) * 100).toFixed(1)}%)`);
  lines.push(`- ❌ Broken Links: ${report.brokenLinks} (${((report.brokenLinks / report.totalLinks) * 100).toFixed(1)}%)`);
  lines.push(`- 🔀 Redirects: ${report.redirects}`);
  lines.push(`- ⚠️ Errors: ${report.errors}`);
  lines.push(`- Average Response Time: ${report.summary.averageResponseTime.toFixed(0)}ms`);
  lines.push('');
  
  lines.push('## Status Distribution');
  for (const [status, count] of Object.entries(report.summary.byStatus)) {
    lines.push(`- ${status}: ${count} links`);
  }
  lines.push('');
  
  // Show broken links
  const brokenLinks = report.results.filter(r => !r.valid && r.status >= 400);
  if (brokenLinks.length > 0) {
    lines.push('## Broken Links');
    lines.push('');
    lines.push('| Resource | URL | Status | Error |');
    lines.push('|----------|-----|--------|-------|');
    for (const link of brokenLinks) {
      const resource = link.resourceTitle || 'Unknown';
      const status = `${link.status} ${link.statusText}`;
      const error = link.error || '-';
      lines.push(`| ${resource} | ${link.url} | ${status} | ${error} |`);
    }
    lines.push('');
  }
  
  // Show redirects
  const redirectedLinks = report.results.filter(r => r.redirectUrl);
  if (redirectedLinks.length > 0) {
    lines.push('## Redirected Links');
    lines.push('');
    lines.push('| Resource | Original URL | Redirect To |');
    lines.push('|----------|--------------|-------------|');
    for (const link of redirectedLinks) {
      const resource = link.resourceTitle || 'Unknown';
      lines.push(`| ${resource} | ${link.url} | ${link.redirectUrl || 'N/A'} |`);
    }
    lines.push('');
  }
  
  // Show slow links
  const slowLinks = report.results
    .filter(r => r.responseTime > 5000)
    .sort((a, b) => b.responseTime - a.responseTime)
    .slice(0, 10);
    
  if (slowLinks.length > 0) {
    lines.push('## Slowest Links (>5s)');
    lines.push('');
    lines.push('| Resource | URL | Response Time |');
    lines.push('|----------|-----|---------------|');
    for (const link of slowLinks) {
      const resource = link.resourceTitle || 'Unknown';
      lines.push(`| ${resource} | ${link.url} | ${(link.responseTime / 1000).toFixed(1)}s |`);
    }
  }
  
  return lines.join('\n');
}

/**
 * Second-pass verification with a real browser User-Agent (strict dead-link
 * policy, per .agents/memory/link-scan-false-positives.md): a datacenter-IP
 * scan over-flags by ~100x because sites bot-block HEAD/bot-UA requests with
 * 403/429/connect-timeouts. Only classify as dead:
 *   - DNS ENOTFOUND
 *   - ECONNREFUSED
 *   - browser-UA-confirmed HTTP 404/410
 *   - SSL certificate failures (browsers block those for humans too)
 * Everything else (403/401/429/999, 5xx, timeouts, resets) is treated as
 * bot-block/temporary and must NOT appear as a problem link.
 */

const BROWSER_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

export interface BrowserVerification {
  /** HTTP status number, or an "ERR:<code>" string for network failures */
  status: number | string;
  finalUrl?: string;
  /** true only when the strict dead-link policy confirms the link is dead */
  confirmedDead: boolean;
  /** true when the browser-UA GET got a 2xx/3xx (definitively alive) */
  confirmedAlive: boolean;
  /** human-readable classification for the errorMessage column */
  verdict: string;
}

export function classifyBrowserVerification(status: number | string): Pick<BrowserVerification, 'confirmedDead' | 'confirmedAlive' | 'verdict'> {
  if (typeof status === 'string') {
    if (status.includes('ENOTFOUND')) return { confirmedDead: true, confirmedAlive: false, verdict: 'dead: DNS not found (browser-UA verified)' };
    if (status.includes('ECONNREFUSED')) return { confirmedDead: true, confirmedAlive: false, verdict: 'dead: connection refused (browser-UA verified)' };
    // Note: missing-intermediate chains (UNABLE_TO_VERIFY_LEAF_SIGNATURE /
    // UNABLE_TO_GET_ISSUER_CERT*) are given an AIA chain-completion retry in
    // browserVerifyLink BEFORE reaching this classifier — browsers recover
    // from those via Authority Information Access, so only chains that still
    // fail after completion land here (and are then genuinely dead).
    if (/CERT|LEAF_SIGNATURE|UNABLE_TO_VERIFY|SELF_SIGNED|DEPTH_ZERO|ALTNAME/i.test(status)) {
      return { confirmedDead: true, confirmedAlive: false, verdict: `dead: SSL failure (${status})` };
    }
    // Connect timeouts / resets from a datacenter IP are the classic
    // bot-block signature (e.g. UND_ERR_CONNECT_TIMEOUT) — never dead.
    return { confirmedDead: false, confirmedAlive: false, verdict: `likely bot-block (${status} under browser UA)` };
  }
  if (status >= 200 && status < 400) return { confirmedDead: false, confirmedAlive: true, verdict: `alive: ${status} under browser UA (bot-block false positive)` };
  if (status === 404 || status === 410) return { confirmedDead: true, confirmedAlive: false, verdict: `dead: ${status} confirmed under browser UA` };
  // 401/403/429/999, 5xx and anything else: bot-block, auth wall, or
  // transient server trouble — alive per the strict policy.
  return { confirmedDead: false, confirmedAlive: false, verdict: `likely bot-block/auth wall (${status} under browser UA)` };
}

/**
 * TLS errors that mean "the server forgot to send its intermediate cert" —
 * every mainstream browser recovers from these via the AIA (Authority
 * Information Access) CA-Issuers URL in the leaf certificate, so they must
 * not be treated as hard-dead until an AIA chain-completion retry also fails.
 */
const MISSING_INTERMEDIATE_CODES = /UNABLE_TO_VERIFY_LEAF_SIGNATURE|UNABLE_TO_GET_ISSUER_CERT/i;

/** System trust anchors parsed once, grouped by subject for issuer lookup. */
let systemRootsBySubject: Map<string, X509Certificate[]> | null = null;
function getSystemRoots(): Map<string, X509Certificate[]> {
  if (!systemRootsBySubject) {
    systemRootsBySubject = new Map();
    for (const pem of tls.rootCertificates) {
      try {
        const cert = new X509Certificate(pem);
        const list = systemRootsBySubject.get(cert.subject) ?? [];
        list.push(cert);
        systemRootsBySubject.set(cert.subject, list);
      } catch { /* skip unparseable roots */ }
    }
  }
  return systemRootsBySubject;
}

/**
 * Validate an AIA-downloaded chain WITHOUT ever promoting downloaded certs to
 * trust anchors: every signature is verified link-by-link, every cert must be
 * a currently-valid CA cert (except the leaf), the leaf must match the target
 * hostname, and the terminal issuer must be an EXISTING platform system root.
 * A hostile endpoint publishing AIA links to its own intermediate/self-signed
 * root fails here — the downloaded chain never reaches a system trust anchor.
 * Exported for regression coverage (scripts/validation/tls-recovery-check.ts).
 */
export function validateAiaChain(
  leaf: X509Certificate,
  intermediates: X509Certificate[],
  hostname: string,
  now: Date = new Date(),
): boolean {
  const within = (c: X509Certificate) => now >= new Date(c.validFrom) && now <= new Date(c.validTo);
  try {
    if (intermediates.length === 0) return false;
    if (!within(leaf)) return false;
    if (!leaf.checkHost(hostname)) return false;
    let current = leaf;
    for (const inter of intermediates) {
      if (!inter.ca) return false; // downloaded cert is not a CA cert
      if (inter.subject === inter.issuer) return false; // never accept a downloaded root
      if (!within(inter)) return false;
      if (!current.checkIssued(inter)) return false;
      if (!current.verify(inter.publicKey)) return false; // signature check
      current = inter;
    }
    // The last downloaded intermediate must be signed by a platform root.
    const candidates = getSystemRoots().get(current.issuer) ?? [];
    return candidates.some(root => {
      try {
        return within(root) && current.checkIssued(root) && current.verify(root.publicKey);
      } catch {
        return false;
      }
    });
  } catch {
    return false;
  }
}

/**
 * SSRF guard for AIA "CA Issuers" URLs: those URLs come from an UNVERIFIED
 * peer certificate, i.e. fully attacker-controlled input, so the downloader
 * must never be usable to reach internal services or cloud metadata.
 * Exported for regression coverage (scripts/validation/tls-recovery-check.ts).
 */
export function isPrivateAddress(ip: string): boolean {
  const family = net.isIP(ip);
  if (family === 4) {
    const parts = ip.split('.').map(Number);
    if (parts.length !== 4 || parts.some(p => Number.isNaN(p))) return true;
    const [a, b] = parts;
    return (
      a === 0 || a === 10 || a === 127 ||
      (a === 100 && b >= 64 && b <= 127) ||       // CGNAT 100.64/10
      (a === 169 && b === 254) ||                  // link-local / cloud metadata
      (a === 172 && b >= 16 && b <= 31) ||
      (a === 192 && b === 168) ||
      (a === 192 && b === 0) ||                    // 192.0.0/24 + 192.0.2/24 doc
      (a === 198 && (b === 18 || b === 19)) ||     // benchmarking
      (a === 198 && b === 51) || (a === 203 && b === 113) || // doc ranges
      a >= 224                                     // multicast + reserved + broadcast
    );
  }
  if (family === 6) {
    const lower = ip.toLowerCase();
    // IPv4-mapped/compatible: validate the embedded IPv4.
    const v4 = lower.match(/(\d+\.\d+\.\d+\.\d+)$/);
    if (v4) return isPrivateAddress(v4[1]);
    return (
      lower === '::' || lower === '::1' ||
      lower.startsWith('fe8') || lower.startsWith('fe9') ||
      lower.startsWith('fea') || lower.startsWith('feb') || // fe80::/10 link-local
      lower.startsWith('fc') || lower.startsWith('fd') ||   // fc00::/7 ULA
      lower.startsWith('ff') ||                             // multicast
      lower.startsWith('64:ff9b')                           // NAT64 (embeds v4)
    );
  }
  return true; // not a parseable IP → treat as unsafe
}

/**
 * Download an AIA CA-Issuers URL with SSRF controls:
 *  - http(s) only, no credentials in the URL
 *  - hostname resolved once; ALL resolved addresses must be public
 *  - the connection is pinned to the validated address (custom lookup), so a
 *    DNS-rebinding second resolution can never redirect the socket
 *  - redirects are refused entirely (CA issuer URLs are direct downloads)
 * Returns the response body, or null when anything is off. Exported for
 * regression coverage.
 */
export async function fetchAiaUrlSafely(rawUrl: string, timeoutMs: number): Promise<Buffer | null> {
  let u: URL;
  try { u = new URL(rawUrl); } catch { return null; }
  if (u.protocol !== 'http:' && u.protocol !== 'https:') return null;
  if (u.username || u.password) return null;

  const host = u.hostname.replace(/^\[|\]$/g, '');
  let pinnedAddress: string;
  if (net.isIP(host)) {
    pinnedAddress = host;
  } else {
    let resolved: Array<{ address: string; family: number }>;
    try {
      resolved = await dnsLookup(host, { all: true });
    } catch {
      return null;
    }
    if (resolved.length === 0 || resolved.some(a => isPrivateAddress(a.address))) return null;
    pinnedAddress = resolved[0].address;
  }
  if (isPrivateAddress(pinnedAddress)) return null;

  const pinnedFamily = net.isIP(pinnedAddress);
  // Pin every connection this agent makes to the pre-validated address.
  const pinnedLookup = (_hostname: string, options: any, cb: any) => {
    if (options && options.all) cb(null, [{ address: pinnedAddress, family: pinnedFamily }]);
    else cb(null, pinnedAddress, pinnedFamily);
  };
  const agent = u.protocol === 'https:'
    ? new https.Agent({ lookup: pinnedLookup as any })
    : new http.Agent({ lookup: pinnedLookup as any });

  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const res = await fetch(u.toString(), {
      method: 'GET',
      redirect: 'manual', // never follow: a redirect could point anywhere
      signal: ctrl.signal,
      agent,
      size: 262144, // an intermediate cert is a few KB; hard-cap the body
    } as any);
    if (res.status < 200 || res.status >= 300) return null;
    return Buffer.from(await res.arrayBuffer());
  } catch {
    return null;
  } finally {
    clearTimeout(t);
    agent.destroy();
  }
}

/**
 * Fetch the peer's leaf certificate without verification, then walk the AIA
 * "CA Issuers" URLs to download the missing intermediate(s). The downloads
 * are UNTRUSTED input — callers must pass them through validateAiaChain.
 */
async function fetchAiaLeafAndIntermediates(url: string, timeoutMs: number): Promise<{ leaf: X509Certificate; intermediates: X509Certificate[] } | null> {
  const parsed = new URL(url);
  if (parsed.protocol !== 'https:') return null;
  const leaf = await new Promise<X509Certificate | null>((resolve) => {
    const sock = tls.connect(
      {
        host: parsed.hostname,
        port: Number(parsed.port) || 443,
        servername: parsed.hostname,
        rejectUnauthorized: false,
        timeout: timeoutMs,
      },
      () => {
        const cert = sock.getPeerX509Certificate() ?? null;
        sock.destroy();
        resolve(cert);
      },
    );
    sock.on('error', () => resolve(null));
    sock.on('timeout', () => { sock.destroy(); resolve(null); });
  });

  if (!leaf) return null;

  const intermediates: X509Certificate[] = [];
  let current: X509Certificate = leaf;
  for (let depth = 0; depth < 3; depth++) {
    const aia = current.infoAccess?.match(/CA Issuers - URI:(\S+)/);
    if (!aia) break;
    try {
      const body = await fetchAiaUrlSafely(aia[1], timeoutMs);
      if (!body) break;
      const issuer = new X509Certificate(body);
      if (issuer.subject === issuer.issuer) break; // self-signed root: never collect
      intermediates.push(issuer);
      current = issuer;
    } catch {
      break;
    }
  }
  return { leaf, intermediates };
}

/**
 * Retry the browser-UA GET with the AIA-downloaded intermediates appended to
 * the trust bundle — exactly the recovery a real browser performs. Returns
 * null when no recovery was possible (no AIA, download failed, or the chain
 * still doesn't verify — e.g. untrusted root, expired intermediate).
 */
async function retryWithCompletedChain(url: string, timeoutMs: number): Promise<{ status: number; finalUrl?: string } | null> {
  const fetched = await fetchAiaLeafAndIntermediates(url, timeoutMs);
  if (!fetched || fetched.intermediates.length === 0) return null;
  // Trust boundary: the downloaded chain must first verify link-by-link up to
  // an EXISTING system root (signatures, CA flag, validity, hostname). Only
  // then are the proven intermediates supplied for the retry — a private or
  // attacker-published chain is rejected here and stays dead.
  if (!validateAiaChain(fetched.leaf, fetched.intermediates, new URL(url).hostname)) return null;
  const agent = new https.Agent({ ca: [...tls.rootCertificates, ...fetched.intermediates.map(c => c.toString())] });
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const r = await fetch(url, {
      method: 'GET',
      redirect: 'follow',
      signal: ctrl.signal,
      agent: (parsedUrl: URL) => (parsedUrl.protocol === 'https:' ? agent : undefined),
      headers: {
        'User-Agent': BROWSER_UA,
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
      },
    } as any);
    try { (r.body as any)?.destroy?.(); } catch { /* ignore */ }
    return { status: r.status, finalUrl: r.url };
  } catch {
    return null; // chain STILL invalid (or network flake) — caller keeps the dead verdict
  } finally {
    clearTimeout(t);
    agent.destroy();
  }
}

export async function browserVerifyLink(url: string, timeoutMs = 15000): Promise<BrowserVerification> {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    const r = await fetch(url, {
      method: 'GET',
      redirect: 'follow',
      signal: ctrl.signal,
      headers: {
        'User-Agent': BROWSER_UA,
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
      },
    });
    // Drain/cancel the body so sockets are released promptly.
    try { await (r.body as any)?.cancel?.(); } catch { /* ignore */ }
    return { status: r.status, finalUrl: r.url, ...classifyBrowserVerification(r.status) };
  } catch (e: any) {
    const rawCode = String(e?.cause?.code || e?.code || e?.name || 'unknown');
    const code = 'ERR:' + rawCode;
    // Missing-intermediate chains are browser-recoverable via AIA — retry
    // with the completed chain before declaring the link dead.
    if (MISSING_INTERMEDIATE_CODES.test(rawCode)) {
      const recovered = await retryWithCompletedChain(url, timeoutMs);
      if (recovered && recovered.status >= 200 && recovered.status < 400) {
        return {
          status: recovered.status,
          finalUrl: recovered.finalUrl,
          confirmedDead: false,
          confirmedAlive: true,
          verdict: `alive: ${recovered.status} after AIA chain completion (server omits intermediate cert; browsers recover — not dead)`,
        };
      }
      // No recovery: fall through to the strict SSL-failure classification.
    }
    return { status: code, ...classifyBrowserVerification(code) };
  } finally {
    clearTimeout(t);
  }
}

/**
 * Check links from resource objects
 */
export async function checkResourceLinks(
  resources: Array<{ id: number; title: string; url: string }>,
  options?: LinkCheckOptions
): Promise<LinkCheckReport> {
  const checker = new LinkChecker(options);
  const links = resources.map(r => ({
    url: r.url,
    title: r.title,
    id: r.id
  }));
  
  return checker.checkLinks(links);
}