-- Intentionally neutralized before its first production application.
--
-- The original version created pg_trgm and four extension-owned indexes.
-- Replit Publish derives production DDL from the development/prod schema
-- difference and does not provision optional extensions, so those indexes
-- made Publish generate invalid SQL. Typo recovery now uses bounded,
-- deterministic application scoring after a scoped FTS miss; built-in FTS
-- remains indexed by idx_resources_search_tsv.
--
-- Keep this journaled migration as a no-op: development already recorded its
-- historical version, while fresh databases must reproduce the extension-free
-- schema source exactly.
-- No SQL statement is intentionally present below this comment.
