// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-kit/BrandInAction.tsx": () => import("../components/mockups/brand-kit/BrandInAction.tsx"),
  "./components/mockups/brand-kit/ColorType.tsx": () => import("../components/mockups/brand-kit/ColorType.tsx"),
  "./components/mockups/brand-kit/Guidelines.tsx": () => import("../components/mockups/brand-kit/Guidelines.tsx"),
  "./components/mockups/brand-kit/LogoSystem.tsx": () => import("../components/mockups/brand-kit/LogoSystem.tsx"),
  "./components/mockups/awesome-video-ds/ComponentsPatterns.tsx": () => import("../components/mockups/awesome-video-ds/ComponentsPatterns.tsx"),
  "./components/mockups/awesome-video-ds/Foundations.tsx": () => import("../components/mockups/awesome-video-ds/Foundations.tsx"),
  "./components/mockups/awesome-video-ds/IntegrationGovernance.tsx": () => import("../components/mockups/awesome-video-ds/IntegrationGovernance.tsx")
};
