import { sql } from 'drizzle-orm';
import { pgTable, text, serial, varchar, timestamp, integer, boolean, jsonb, index, uuid, primaryKey, unique } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

/**
 * Session storage table for Replit Auth
 *
 * Stores HTTP session data for authenticated users using Passport.js and connect-pg-simple.
 * Sessions are automatically cleaned up after expiration.
 *
 * @property {string} sid - Session identifier (primary key), generated by express-session
 * @property {object} sess - Session data stored as JSON (user info, passport data, etc.)
 * @property {timestamp} expire - Session expiration timestamp, indexed for efficient cleanup
 *
 * Indexes:
 * - IDX_session_expire: On expire column for fast expiration queries
 */
export const sessions = pgTable(
  "sessions",
  {
    sid: varchar("sid").primaryKey(),
    sess: jsonb("sess").notNull(),
    expire: timestamp("expire").notNull(),
  },
  (table) => [index("IDX_session_expire").on(table.expire)],
);

/**
 * Users table for authentication and user management
 *
 * Supports both Replit OAuth and local authentication. Users can have different roles
 * for authorization (user, admin, moderator).
 *
 * @property {string} id - UUID primary key, auto-generated using gen_random_uuid()
 * @property {string} email - User email address, unique constraint for login
 * @property {string} password - Hashed password using bcrypt (only for local auth, null for OAuth)
 * @property {string} firstName - User's first name from profile
 * @property {string} lastName - User's last name from profile
 * @property {string} profileImageUrl - URL to user's profile picture (from OAuth or uploaded)
 * @property {string} role - User role: 'user' (default), 'admin', or 'moderator'
 * @property {timestamp} createdAt - Account creation timestamp
 * @property {timestamp} updatedAt - Last profile update timestamp
 *
 * Constraints:
 * - Email must be unique
 * - ID is auto-generated UUID
 *
 * Referenced by:
 * - resources.submittedBy, resources.approvedBy
 * - resourceEdits.submittedBy, resourceEdits.handledBy
 * - userFavorites.userId
 * - userBookmarks.userId
 * - userJourneyProgress.userId
 * - userPreferences.userId
 * - userInteractions.userId
 * - resourceAuditLog.performedBy
 * - githubSyncHistory.performedBy
 * - enrichmentJobs.startedBy
 */
export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  email: varchar("email").unique(),
  password: varchar("password"), // For local authentication (hashed with bcrypt)
  firstName: varchar("first_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  role: text("role").default("user"), // user, admin, moderator
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export type UpsertUser = typeof users.$inferInsert;
export type User = typeof users.$inferSelect;

/**
 * API Keys table for programmatic API access
 *
 * Stores API keys for third-party integrations and programmatic access to resources.
 * Keys are hashed using bcrypt before storage for security. Only the plaintext key is
 * shown once during creation.
 *
 * @property {string} id - UUID primary key, auto-generated using gen_random_uuid()
 * @property {string} userId - Reference to user who owns this API key (cascades on delete)
 * @property {string} key - Hashed API key using bcrypt (unique constraint)
 * @property {string} name - User-provided label/description for the key (e.g., "My IDE Extension")
 * @property {object} scopes - JSON array of permission scopes (e.g., ["read:resources", "read:tags"])
 * @property {timestamp} createdAt - When the API key was created
 * @property {timestamp} lastUsedAt - Last time the key was used for authentication (null if never used)
 * @property {timestamp} expiresAt - Optional expiration timestamp (null for non-expiring keys)
 * @property {timestamp} revokedAt - When the key was revoked (null if active)
 *
 * Constraints:
 * - Key must be unique (hashed value)
 * - userId cascades on delete (removes API keys when user deleted)
 *
 * Indexes:
 * - idx_api_keys_user_id: Fast lookup of keys by user
 * - idx_api_keys_key: Fast authentication lookups by hashed key
 * - idx_api_keys_expires_at: Efficient expiration cleanup queries
 *
 * Security Notes:
 * - Keys are hashed with bcrypt before storage
 * - Plaintext key only returned once during creation
 * - Revoked keys (revokedAt != null) cannot be used
 * - Expired keys (expiresAt < now) cannot be used
 */
export const apiKeys = pgTable(
  "api_keys",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    key: varchar("key").notNull().unique(),
    name: varchar("name").notNull(),
    scopes: jsonb("scopes").$type<string[]>().default([]).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    lastUsedAt: timestamp("last_used_at"),
    expiresAt: timestamp("expires_at"),
    revokedAt: timestamp("revoked_at"),
  },
  (table) => [
    index("idx_api_keys_user_id").on(table.userId),
    index("idx_api_keys_key").on(table.key),
    index("idx_api_keys_expires_at").on(table.expiresAt),
  ]
);

export type InsertApiKey = typeof apiKeys.$inferInsert;
export type ApiKey = typeof apiKeys.$inferSelect;

/**
 * Resources table - Core content entity
 *
 * Stores curated video resources with approval workflow and GitHub synchronization.
 * Supports 3-level categorization (category > subcategory > sub-subcategory).
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} title - Resource title/name (required)
 * @property {string} url - Resource URL, must be unique to prevent duplicates
 * @property {string} description - Resource description or summary (defaults to empty string)
 * @property {string} category - Top-level category (required, e.g., "Frameworks", "Languages")
 * @property {string} subcategory - Second-level category (optional)
 * @property {string} subSubcategory - Third-level category (optional)
 * @property {string} status - Approval status: 'pending', 'approved', 'rejected', or 'archived' (default: 'approved')
 * @property {string} submittedBy - User ID who submitted the resource (cascades on user delete)
 * @property {string} approvedBy - User ID who approved the resource
 * @property {timestamp} approvedAt - When the resource was approved
 * @property {boolean} githubSynced - Whether resource has been synced to GitHub (default: false)
 * @property {timestamp} lastSyncedAt - Last GitHub sync timestamp
 * @property {object} metadata - Flexible JSON metadata (AI enrichment data, tags, etc.)
 * @property {timestamp} createdAt - Resource creation timestamp
 * @property {timestamp} updatedAt - Last modification timestamp
 *
 * Constraints:
 * - URL must be unique (prevents duplicate resources)
 * - submittedBy cascades on delete (removes resources when user deleted)
 *
 * Indexes:
 * - idx_resources_status: Fast filtering by approval status
 * - idx_resources_status_category: Combined status + category queries
 * - idx_resources_category: Fast category browsing
 *
 * Referenced by:
 * - resourceEdits.resourceId
 * - resourceTags (many-to-many)
 * - journeySteps.resourceId
 * - userFavorites (many-to-many)
 * - userBookmarks (many-to-many)
 * - userInteractions.resourceId
 * - resourceAuditLog.resourceId
 * - enrichmentQueue.resourceId
 */
export const resources = pgTable(
  "resources",
  {
    id: serial("id").primaryKey(),
    title: text("title").notNull(),
    url: text("url").notNull().unique(), // BUG #4 FIX: Prevent duplicate URLs
    description: text("description").notNull().default(""),
    category: text("category").notNull(),
    subcategory: text("subcategory"),
    subSubcategory: text("sub_subcategory"),
    status: text("status").default("approved"), // pending, approved, rejected, archived
    submittedBy: varchar("submitted_by").references(() => users.id, { onDelete: "cascade" }),
    approvedBy: varchar("approved_by").references(() => users.id),
    approvedAt: timestamp("approved_at"),
    githubSynced: boolean("github_synced").default(false),
    lastSyncedAt: timestamp("last_synced_at"),
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    index("idx_resources_status").on(table.status),
    index("idx_resources_status_category").on(table.status, table.category),
    index("idx_resources_category").on(table.category),
  ]
);

export const insertResourceSchema = createInsertSchema(resources).pick({
  title: true,
  url: true,
  description: true,
  category: true,
  subcategory: true,
  subSubcategory: true,
  status: true,
  submittedBy: true,
  metadata: true,
});

export type InsertResource = z.infer<typeof insertResourceSchema>;
export type Resource = typeof resources.$inferSelect;

/**
 * Resource Edits table - Crowdsourced edit suggestions
 *
 * Implements a suggest-edit workflow allowing users to propose changes to existing resources.
 * Includes AI-powered analysis via Claude for quality suggestions.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {number} resourceId - Reference to the resource being edited (required)
 * @property {string} submittedBy - User who submitted the edit suggestion (required)
 * @property {string} status - Edit status: 'pending', 'approved', or 'rejected' (default: 'pending')
 * @property {timestamp} originalResourceUpdatedAt - Timestamp of resource when edit was created (for conflict detection)
 * @property {object} proposedChanges - Field-by-field changes showing old vs new values
 * @property {object} proposedData - Complete proposed resource data after changes applied
 * @property {object} claudeMetadata - AI-generated suggestions and analysis (title, description, tags, category, confidence, topics)
 * @property {timestamp} claudeAnalyzedAt - When Claude analyzed the edit suggestion
 * @property {string} handledBy - Admin/moderator who approved or rejected the edit
 * @property {timestamp} handledAt - When the edit was approved or rejected
 * @property {string} rejectionReason - Explanation if edit was rejected
 * @property {timestamp} createdAt - Edit suggestion creation timestamp
 * @property {timestamp} updatedAt - Last modification timestamp
 *
 * Indexes:
 * - idx_resource_edits_resource_id: Fast lookup of edits for a specific resource
 * - idx_resource_edits_status: Filter pending/approved/rejected edits
 * - idx_resource_edits_submitted_by: Track edits by user
 *
 * Relationships:
 * - References resources.id (the resource being edited)
 * - References users.id for submittedBy and handledBy
 */
export const resourceEdits = pgTable(
  "resource_edits",
  {
    id: serial("id").primaryKey(),
    resourceId: integer("resource_id").references(() => resources.id).notNull(),
    submittedBy: varchar("submitted_by").references(() => users.id).notNull(),
    status: text("status").$type<"pending" | "approved" | "rejected">().default("pending").notNull(),

    originalResourceUpdatedAt: timestamp("original_resource_updated_at").notNull(),

    proposedChanges: jsonb("proposed_changes").$type<Record<string, { old: any; new: any }>>().notNull(),
    proposedData: jsonb("proposed_data").$type<Partial<Resource>>().notNull(),

    claudeMetadata: jsonb("claude_metadata").$type<{
      suggestedTitle?: string;
      suggestedDescription?: string;
      suggestedTags?: string[];
      suggestedCategory?: string;
      suggestedSubcategory?: string;
      confidence?: number;
      keyTopics?: string[];
    }>(),
    claudeAnalyzedAt: timestamp("claude_analyzed_at"),

    handledBy: varchar("handled_by").references(() => users.id),
    handledAt: timestamp("handled_at"),
    rejectionReason: text("rejection_reason"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("idx_resource_edits_resource_id").on(table.resourceId),
    index("idx_resource_edits_status").on(table.status),
    index("idx_resource_edits_submitted_by").on(table.submittedBy),
  ]
);

export const insertResourceEditSchema = createInsertSchema(resourceEdits).pick({
  resourceId: true,
  submittedBy: true,
  status: true,
  originalResourceUpdatedAt: true,
  proposedChanges: true,
  proposedData: true,
  claudeMetadata: true,
  claudeAnalyzedAt: true,
});

export type InsertResourceEdit = z.infer<typeof insertResourceEditSchema>;
export type ResourceEdit = typeof resourceEdits.$inferSelect;

/**
 * Categories table - Top-level taxonomy
 *
 * Defines the primary categorization for resources (e.g., "Frameworks", "Languages", "Tools").
 * Forms the root of a 3-level hierarchy: category > subcategory > sub-subcategory.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} name - Display name of the category (required, unique)
 * @property {string} slug - URL-friendly identifier (required, unique, used in routing)
 *
 * Constraints:
 * - Both name and slug must be unique
 *
 * Referenced by:
 * - subcategories.categoryId (one-to-many)
 */
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  slug: text("slug").notNull().unique(),
});

export const insertCategorySchema = createInsertSchema(categories).pick({
  name: true,
  slug: true,
});

export const updateCategorySchema = insertCategorySchema.partial();

export type InsertCategory = z.infer<typeof insertCategorySchema>;
export type UpdateCategory = z.infer<typeof updateCategorySchema>;
export type Category = typeof categories.$inferSelect;

/**
 * Subcategories table - Second-level taxonomy
 *
 * Defines subcategories within a parent category (e.g., "React" under "Frameworks").
 * Part of a 3-level hierarchy: category > subcategory > sub-subcategory.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} name - Display name of the subcategory (required)
 * @property {string} slug - URL-friendly identifier (required)
 * @property {number} categoryId - Parent category reference (cascades on delete)
 *
 * Constraints:
 * - Unique constraint on (slug, categoryId) to prevent duplicate subcategories within same category
 * - Cascades delete when parent category is deleted
 *
 * Relationships:
 * - References categories.id (many-to-one)
 *
 * Referenced by:
 * - subSubcategories.subcategoryId (one-to-many)
 */
export const subcategories = pgTable("subcategories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  categoryId: integer("category_id").references(() => categories.id, { onDelete: "cascade" }),
}, (table) => [
  // BUG #3 FIX: Prevent duplicate subcategories within same category
  unique("subcategories_slug_category_unique").on(table.slug, table.categoryId),
]);

export const insertSubcategorySchema = createInsertSchema(subcategories).pick({
  name: true,
  slug: true,
  categoryId: true,
});

export const updateSubcategorySchema = insertSubcategorySchema.partial();

export type InsertSubcategory = z.infer<typeof insertSubcategorySchema>;
export type UpdateSubcategory = z.infer<typeof updateSubcategorySchema>;
export type Subcategory = typeof subcategories.$inferSelect;

/**
 * Sub-subcategories table - Third-level taxonomy
 *
 * Defines the most granular categorization level (e.g., "Hooks" under "React" under "Frameworks").
 * Completes the 3-level hierarchy: category > subcategory > sub-subcategory.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} name - Display name of the sub-subcategory (required)
 * @property {string} slug - URL-friendly identifier (required)
 * @property {number} subcategoryId - Parent subcategory reference (cascades on delete)
 *
 * Constraints:
 * - Unique constraint on (slug, subcategoryId) to prevent duplicate sub-subcategories within same subcategory
 * - Cascades delete when parent subcategory is deleted
 *
 * Relationships:
 * - References subcategories.id (many-to-one)
 */
export const subSubcategories = pgTable("sub_subcategories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  subcategoryId: integer("subcategory_id").references(() => subcategories.id, { onDelete: "cascade" }),
}, (table) => [
  // Prevent duplicate sub-subcategories within same subcategory
  unique("sub_subcategories_slug_subcategory_unique").on(table.slug, table.subcategoryId),
]);

export const insertSubSubcategorySchema = createInsertSchema(subSubcategories).pick({
  name: true,
  slug: true,
  subcategoryId: true,
});

export const updateSubSubcategorySchema = insertSubSubcategorySchema.partial();

export type InsertSubSubcategory = z.infer<typeof insertSubSubcategorySchema>;
export type UpdateSubSubcategory = z.infer<typeof updateSubSubcategorySchema>;
export type SubSubcategory = typeof subSubcategories.$inferSelect;

/**
 * Awesome Lists table - External curated lists
 *
 * Stores references to external "Awesome List" repositories for importing resources.
 * Enables bulk import from community-curated awesome-* GitHub repositories.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} title - Name of the awesome list (required)
 * @property {string} description - Description of the list's focus and content (defaults to empty string)
 * @property {string} repoUrl - GitHub repository URL (required, e.g., "https://github.com/sindresorhus/awesome")
 * @property {string} sourceUrl - Direct URL to the raw markdown file for parsing (required)
 */
export const awesomeLists = pgTable("awesome_lists", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  repoUrl: text("repo_url").notNull(),
  sourceUrl: text("source_url").notNull(),
});

export const insertAwesomeListSchema = createInsertSchema(awesomeLists).pick({
  title: true,
  description: true,
  repoUrl: true,
  sourceUrl: true,
});

export type InsertAwesomeList = z.infer<typeof insertAwesomeListSchema>;
export type AwesomeList = typeof awesomeLists.$inferSelect;

/**
 * Tags table - Flexible resource labeling
 *
 * Stores tags for cross-cutting resource organization beyond hierarchical categories.
 * Tags enable discovery via topics like "tutorial", "beginner-friendly", "video", etc.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} name - Display name of the tag (required, unique)
 * @property {string} slug - URL-friendly identifier (required, unique)
 * @property {timestamp} createdAt - Tag creation timestamp
 *
 * Constraints:
 * - Both name and slug must be unique
 *
 * Referenced by:
 * - resourceTags (many-to-many with resources)
 */
export const tags = pgTable("tags", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  slug: text("slug").notNull().unique(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertTagSchema = createInsertSchema(tags).pick({
  name: true,
  slug: true,
});

export type InsertTag = z.infer<typeof insertTagSchema>;
export type Tag = typeof tags.$inferSelect;

/**
 * Resource Tags junction table - Many-to-many relationship
 *
 * Links resources to tags, enabling flexible multi-tag categorization.
 * One resource can have many tags, and one tag can apply to many resources.
 *
 * @property {number} resourceId - Reference to the resource (required, cascades on delete)
 * @property {number} tagId - Reference to the tag (required, cascades on delete)
 *
 * Constraints:
 * - Composite primary key on (resourceId, tagId) prevents duplicate tag assignments
 * - Both foreign keys cascade delete (removing resource or tag removes the association)
 *
 * Relationships:
 * - References resources.id (many-to-many)
 * - References tags.id (many-to-many)
 */
export const resourceTags = pgTable(
  "resource_tags",
  {
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    tagId: integer("tag_id").references(() => tags.id, { onDelete: "cascade" }).notNull(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.resourceId, table.tagId] }),
  })
);

/**
 * Learning Journeys table - Structured learning paths
 *
 * Curated sequences of resources forming guided learning paths.
 * Helps users follow a structured curriculum from beginner to advanced topics.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} title - Journey title/name (required, e.g., "React Fundamentals")
 * @property {string} description - Detailed description of learning objectives and outcomes (required)
 * @property {string} difficulty - Skill level: 'beginner', 'intermediate', or 'advanced' (default: 'beginner')
 * @property {string} estimatedDuration - Human-readable time estimate (e.g., "20 hours", "3 weeks")
 * @property {string} icon - Icon identifier for visual representation
 * @property {number} orderIndex - Sort order for displaying journeys
 * @property {string} category - Primary category this journey belongs to (required)
 * @property {string} status - Publication status: 'draft', 'published', or 'archived' (default: 'published')
 * @property {timestamp} createdAt - Journey creation timestamp
 * @property {timestamp} updatedAt - Last modification timestamp
 *
 * Referenced by:
 * - journeySteps (one-to-many)
 * - userJourneyProgress (one-to-many)
 */
export const learningJourneys = pgTable("learning_journeys", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  difficulty: text("difficulty").default("beginner"), // beginner, intermediate, advanced
  estimatedDuration: text("estimated_duration"), // e.g., "20 hours"
  icon: text("icon"),
  orderIndex: integer("order_index"),
  category: text("category").notNull(),
  status: text("status").default("published"), // draft, published, archived
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertLearningJourneySchema = createInsertSchema(learningJourneys).pick({
  title: true,
  description: true,
  difficulty: true,
  estimatedDuration: true,
  icon: true,
  orderIndex: true,
  category: true,
  status: true,
});

export type InsertLearningJourney = z.infer<typeof insertLearningJourneySchema>;
export type LearningJourney = typeof learningJourneys.$inferSelect;

/**
 * Journey Steps table - Individual learning path steps
 *
 * Defines ordered steps within a learning journey, each optionally linked to a resource.
 * Steps can be mandatory or optional, enabling flexible learning paths.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {number} journeyId - Parent learning journey (required, cascades on delete)
 * @property {number} resourceId - Associated resource for this step (optional, cascades on delete)
 * @property {number} stepNumber - Order within the journey (required, determines sequence)
 * @property {string} title - Step title/name (required)
 * @property {string} description - Step description, learning objectives, or instructions
 * @property {boolean} isOptional - Whether this step can be skipped (default: false)
 * @property {timestamp} createdAt - Step creation timestamp
 *
 * Constraints:
 * - Cascades delete when parent journey or linked resource is deleted
 *
 * Indexes:
 * - idx_journey_steps_journey_id: Fast lookup of all steps in a journey
 * - idx_journey_steps_resource_id: Find journeys using a specific resource
 *
 * Relationships:
 * - References learningJourneys.id (many-to-one)
 * - References resources.id (many-to-one, optional)
 *
 * Referenced by:
 * - userJourneyProgress.currentStepId
 */
export const journeySteps = pgTable(
  "journey_steps",
  {
    id: serial("id").primaryKey(),
    journeyId: integer("journey_id").references(() => learningJourneys.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }),
    stepNumber: integer("step_number").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    isOptional: boolean("is_optional").default(false),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("idx_journey_steps_journey_id").on(table.journeyId),
    index("idx_journey_steps_resource_id").on(table.resourceId),
  ]
);

export const insertJourneyStepSchema = createInsertSchema(journeySteps).pick({
  journeyId: true,
  resourceId: true,
  stepNumber: true,
  title: true,
  description: true,
  isOptional: true,
});

export type InsertJourneyStep = z.infer<typeof insertJourneyStepSchema>;
export type JourneyStep = typeof journeySteps.$inferSelect;

/**
 * User Favorites junction table - Many-to-many relationship
 *
 * Tracks which resources users have marked as favorites for quick access.
 * Enables personalized resource collections.
 *
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {number} resourceId - Reference to the favorited resource (required, cascades on delete)
 * @property {timestamp} createdAt - When the resource was favorited
 *
 * Constraints:
 * - Composite primary key on (userId, resourceId) prevents duplicate favorites
 * - Both foreign keys cascade delete (removing user or resource removes the favorite)
 *
 * Relationships:
 * - References users.id (many-to-many)
 * - References resources.id (many-to-many)
 */
export const userFavorites = pgTable(
  "user_favorites",
  {
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.userId, table.resourceId] }),
  })
);

/**
 * User Bookmarks junction table - Many-to-many relationship with notes
 *
 * Tracks bookmarked resources with optional personal notes.
 * Similar to favorites but allows users to add context and reminders.
 *
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {number} resourceId - Reference to the bookmarked resource (required, cascades on delete)
 * @property {string} notes - User's personal notes about the resource (optional)
 * @property {timestamp} createdAt - When the bookmark was created
 *
 * Constraints:
 * - Composite primary key on (userId, resourceId) prevents duplicate bookmarks
 * - Both foreign keys cascade delete (removing user or resource removes the bookmark)
 *
 * Relationships:
 * - References users.id (many-to-many)
 * - References resources.id (many-to-many)
 */
export const userBookmarks = pgTable(
  "user_bookmarks",
  {
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    notes: text("notes"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.userId, table.resourceId] }),
  })
);

/**
 * User Journey Progress table - Learning path tracking
 *
 * Tracks each user's progress through learning journeys, including completed steps
 * and current position. Enables resume functionality and progress analytics.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {number} journeyId - Reference to the learning journey (required, cascades on delete)
 * @property {number} currentStepId - Current step user is on (optional reference to journeySteps)
 * @property {number[]} completedSteps - Array of completed step IDs (default: empty array)
 * @property {timestamp} startedAt - When user started this journey
 * @property {timestamp} lastAccessedAt - Last time user accessed this journey
 * @property {timestamp} completedAt - When user completed all steps (null if incomplete)
 *
 * Constraints:
 * - Unique constraint on (userId, journeyId) - one progress record per user per journey
 * - Cascades delete when user or journey is deleted
 *
 * Indexes:
 * - idx_user_journey_progress_user_id: Find all journeys for a user
 * - idx_user_journey_progress_journey_id: Find all users in a journey
 *
 * Relationships:
 * - References users.id (many-to-one)
 * - References learningJourneys.id (many-to-one)
 * - References journeySteps.id for currentStepId (many-to-one, optional)
 */
export const userJourneyProgress = pgTable(
  "user_journey_progress",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    journeyId: integer("journey_id").references(() => learningJourneys.id, { onDelete: "cascade" }).notNull(),
    currentStepId: integer("current_step_id").references(() => journeySteps.id),
    completedSteps: jsonb("completed_steps").$type<number[]>().default([]),
    startedAt: timestamp("started_at").defaultNow(),
    lastAccessedAt: timestamp("last_accessed_at").defaultNow(),
    completedAt: timestamp("completed_at"),
  },
  (table) => [
    unique("user_journey_unique").on(table.userId, table.journeyId),
    index("idx_user_journey_progress_user_id").on(table.userId),
    index("idx_user_journey_progress_journey_id").on(table.journeyId),
  ]
);

export const insertUserJourneyProgressSchema = createInsertSchema(userJourneyProgress).pick({
  userId: true,
  journeyId: true,
  currentStepId: true,
  completedSteps: true,
});

export type InsertUserJourneyProgress = z.infer<typeof insertUserJourneyProgressSchema>;
export type UserJourneyProgress = typeof userJourneyProgress.$inferSelect;

/**
 * Resource Audit Log table - Change history tracking
 *
 * Maintains a complete audit trail of all resource modifications for compliance,
 * debugging, and analytics. Preserves history even after resource deletion.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {number} resourceId - Current resource reference (nullable, SET NULL on resource delete)
 * @property {number} originalResourceId - Original resource ID, never nullified (preserves history after deletion)
 * @property {string} action - Action type: 'created', 'updated', 'approved', 'rejected', 'synced', 'deleted' (required)
 * @property {string} performedBy - User who performed the action (nullable, SET NULL on user delete)
 * @property {object} changes - JSON object containing changed fields and values
 * @property {string} notes - Optional notes or comments about the change
 * @property {timestamp} createdAt - When the action occurred
 *
 * Constraints:
 * - resourceId uses SET NULL on delete (maintains audit log after resource deletion)
 * - performedBy uses SET NULL on delete (maintains audit log after user deletion)
 * - originalResourceId never changes (preserves original resource ID for historical reference)
 *
 * Relationships:
 * - References resources.id (many-to-one, nullable)
 * - References users.id for performedBy (many-to-one, nullable)
 */
export const resourceAuditLog = pgTable("resource_audit_log", {
  id: serial("id").primaryKey(),
  resourceId: integer("resource_id").references(() => resources.id, { onDelete: "set null" }),
  originalResourceId: integer("original_resource_id"), // Never SET NULL - preserves history after deletion
  action: text("action").notNull(), // created, updated, approved, rejected, synced, deleted
  performedBy: varchar("performed_by").references(() => users.id, { onDelete: "set null" }),
  changes: jsonb("changes").$type<Record<string, any>>(),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});

/**
 * GitHub Sync Queue table - Async GitHub operations
 *
 * Queues GitHub import/export operations for async processing.
 * Enables batch synchronization between database and GitHub repositories.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} repositoryUrl - Target GitHub repository URL (required)
 * @property {string} branch - Target branch name (default: 'main')
 * @property {number[]} resourceIds - Array of resource IDs to sync (default: empty array)
 * @property {string} action - Operation type: 'import' or 'export' (required)
 * @property {string} status - Queue status: 'pending', 'processing', 'completed', or 'failed' (default: 'pending')
 * @property {string} errorMessage - Error details if status is 'failed'
 * @property {object} metadata - Additional sync metadata (default: empty object)
 * @property {timestamp} createdAt - When sync was queued
 * @property {timestamp} processedAt - When sync completed or failed
 *
 * Indexes:
 * - idx_github_sync_queue_status: Fast filtering by status for queue processing
 */
export const githubSyncQueue = pgTable(
  "github_sync_queue",
  {
    id: serial("id").primaryKey(),
    repositoryUrl: text("repository_url").notNull(),
    branch: text("branch").default("main"),
    resourceIds: jsonb("resource_ids").$type<number[]>().default([]),
    action: text("action").notNull(), // import, export
    status: text("status").default("pending"), // pending, processing, completed, failed
    errorMessage: text("error_message"),
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    createdAt: timestamp("created_at").defaultNow(),
    processedAt: timestamp("processed_at"),
  },
  (table) => [
    index("idx_github_sync_queue_status").on(table.status),
  ]
);

export const insertGithubSyncQueueSchema = createInsertSchema(githubSyncQueue).pick({
  repositoryUrl: true,
  branch: true,
  resourceIds: true,
  action: true,
  status: true,
  metadata: true,
});

export type InsertGithubSyncQueue = z.infer<typeof insertGithubSyncQueueSchema>;
export type GithubSyncQueue = typeof githubSyncQueue.$inferSelect;

/**
 * User Preferences table - Personalization settings
 *
 * Stores user preferences for personalized recommendations and content filtering.
 * Enables AI-powered recommendation engine to tailor results to user interests.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {string[]} preferredCategories - Array of preferred category names (default: empty array)
 * @property {string} skillLevel - Self-reported skill: 'beginner', 'intermediate', or 'advanced' (default: 'beginner')
 * @property {string[]} learningGoals - Array of learning objectives (default: empty array)
 * @property {string[]} preferredResourceTypes - Array of preferred content types (default: empty array)
 * @property {string} timeCommitment - Learning frequency: 'daily', 'weekly', or 'flexible' (default: 'flexible')
 * @property {timestamp} createdAt - Preferences creation timestamp
 * @property {timestamp} updatedAt - Last modification timestamp
 *
 * Constraints:
 * - Unique constraint on userId (one preferences record per user)
 * - Cascades delete when user is deleted
 *
 * Indexes:
 * - idx_user_preferences_user_id: Fast user preference lookup
 *
 * Relationships:
 * - References users.id (one-to-one)
 */
export const userPreferences = pgTable(
  "user_preferences",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    preferredCategories: jsonb("preferred_categories").$type<string[]>().default([]),
    skillLevel: text("skill_level").notNull().default("beginner"), // beginner, intermediate, advanced
    learningGoals: jsonb("learning_goals").$type<string[]>().default([]),
    preferredResourceTypes: jsonb("preferred_resource_types").$type<string[]>().default([]),
    timeCommitment: text("time_commitment").default("flexible"), // daily, weekly, flexible
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    index("idx_user_preferences_user_id").on(table.userId),
    unique("user_preferences_user_id_unique").on(table.userId),
  ]
);

export const insertUserPreferencesSchema = createInsertSchema(userPreferences).pick({
  userId: true,
  preferredCategories: true,
  skillLevel: true,
  learningGoals: true,
  preferredResourceTypes: true,
  timeCommitment: true,
});

export type InsertUserPreferences = z.infer<typeof insertUserPreferencesSchema>;
export type UserPreferences = typeof userPreferences.$inferSelect;

/**
 * User Interactions table - Behavioral analytics
 *
 * Tracks all user interactions with resources for analytics and recommendation engine.
 * Enables collaborative filtering and content popularity metrics.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {number} resourceId - Reference to the interacted resource (required, cascades on delete)
 * @property {string} interactionType - Type of interaction: 'view', 'click', 'bookmark', 'rate', 'complete' (required)
 * @property {number} interactionValue - Quantitative value: rating (1-5) or time spent in seconds
 * @property {object} metadata - Additional interaction data (e.g., referrer, device) (default: empty object)
 * @property {timestamp} timestamp - When the interaction occurred
 *
 * Constraints:
 * - Cascades delete when user or resource is deleted
 *
 * Indexes:
 * - idx_user_interactions_user_id: Analytics queries for user behavior
 * - idx_user_interactions_resource_id: Analytics queries for resource popularity
 * - idx_user_interactions_type: Filter by interaction type
 *
 * Relationships:
 * - References users.id (many-to-one)
 * - References resources.id (many-to-one)
 */
export const userInteractions = pgTable(
  "user_interactions",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    interactionType: text("interaction_type").notNull(), // view, click, bookmark, rate, complete
    interactionValue: integer("interaction_value"), // rating (1-5) or time spent
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    timestamp: timestamp("timestamp").defaultNow(),
  },
  (table) => [
    index("idx_user_interactions_user_id").on(table.userId),
    index("idx_user_interactions_resource_id").on(table.resourceId),
    index("idx_user_interactions_type").on(table.interactionType),
  ]
);

export const insertUserInteractionSchema = createInsertSchema(userInteractions).pick({
  userId: true,
  resourceId: true,
  interactionType: true,
  interactionValue: true,
  metadata: true,
});

export type InsertUserInteraction = z.infer<typeof insertUserInteractionSchema>;
export type UserInteraction = typeof userInteractions.$inferSelect;

/**
 * GitHub Sync History table - Sync operation tracking
 *
 * Records every GitHub sync operation with detailed statistics and snapshots.
 * Enables version control, rollback, and sync analytics.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} repositoryUrl - GitHub repository URL that was synced (required)
 * @property {string} direction - Sync direction: 'export' (DB → GitHub) or 'import' (GitHub → DB) (required)
 * @property {string} commitSha - Git commit SHA hash
 * @property {string} commitMessage - Git commit message
 * @property {string} commitUrl - Direct URL to the commit on GitHub
 * @property {number} resourcesAdded - Count of resources added in this sync (default: 0)
 * @property {number} resourcesUpdated - Count of resources updated in this sync (default: 0)
 * @property {number} resourcesRemoved - Count of resources removed in this sync (default: 0)
 * @property {number} totalResources - Total resource count after sync (default: 0)
 * @property {string} performedBy - User who initiated the sync (nullable reference)
 * @property {object} snapshot - Complete resource snapshot at time of sync (default: empty object)
 * @property {object} metadata - Additional sync metadata (default: empty object)
 * @property {timestamp} createdAt - When the sync occurred
 *
 * Indexes:
 * - idx_github_sync_history_repo: Track sync history by repository
 * - idx_github_sync_history_direction: Filter by import/export operations
 *
 * Relationships:
 * - References users.id for performedBy (many-to-one, nullable)
 */
export const githubSyncHistory = pgTable(
  "github_sync_history",
  {
    id: serial("id").primaryKey(),
    repositoryUrl: text("repository_url").notNull(),
    direction: text("direction").notNull(), // export, import
    commitSha: text("commit_sha"),
    commitMessage: text("commit_message"),
    commitUrl: text("commit_url"),
    resourcesAdded: integer("resources_added").default(0),
    resourcesUpdated: integer("resources_updated").default(0),
    resourcesRemoved: integer("resources_removed").default(0),
    totalResources: integer("total_resources").default(0),
    performedBy: varchar("performed_by").references(() => users.id),
    snapshot: jsonb("snapshot").$type<Record<string, any>>().default({}), // Resource snapshot
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("idx_github_sync_history_repo").on(table.repositoryUrl),
    index("idx_github_sync_history_direction").on(table.direction),
  ]
);

export const insertGithubSyncHistorySchema = createInsertSchema(githubSyncHistory).pick({
  repositoryUrl: true,
  direction: true,
  commitSha: true,
  commitMessage: true,
  commitUrl: true,
  resourcesAdded: true,
  resourcesUpdated: true,
  resourcesRemoved: true,
  totalResources: true,
  performedBy: true,
  snapshot: true,
  metadata: true,
});

export type InsertGithubSyncHistory = z.infer<typeof insertGithubSyncHistorySchema>;
export type GithubSyncHistory = typeof githubSyncHistory.$inferSelect;

/**
 * Enrichment Jobs table - Batch AI enrichment tracking
 *
 * Manages batch AI enrichment operations that analyze and enhance resource metadata.
 * Tracks progress, success rates, and errors across large-scale enrichment runs.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} status - Job status: 'pending', 'processing', 'completed', 'failed', 'cancelled' (default: 'pending')
 * @property {string} filter - Resource filter: 'all' or 'unenriched' (default: 'all')
 * @property {number} batchSize - Number of resources to process per batch (default: 10)
 * @property {number} totalResources - Total resources to enrich (default: 0)
 * @property {number} processedResources - Count of processed resources (default: 0)
 * @property {number} successfulResources - Count of successfully enriched resources (default: 0)
 * @property {number} failedResources - Count of failed enrichments (default: 0)
 * @property {number} skippedResources - Count of skipped resources (default: 0)
 * @property {number[]} processedResourceIds - Array of successfully processed resource IDs (default: empty array)
 * @property {number[]} failedResourceIds - Array of failed resource IDs (default: empty array)
 * @property {string} errorMessage - Error details if job failed
 * @property {object} metadata - Additional job metadata (default: empty object)
 * @property {string} startedBy - User who initiated the enrichment job
 * @property {timestamp} startedAt - When processing began
 * @property {timestamp} completedAt - When job finished (success or failure)
 * @property {timestamp} createdAt - Job creation timestamp
 * @property {timestamp} updatedAt - Last status update timestamp
 *
 * Indexes:
 * - idx_enrichment_jobs_status: Fast filtering by job status
 * - idx_enrichment_jobs_started_by: Track jobs by user
 *
 * Relationships:
 * - References users.id for startedBy (many-to-one, nullable)
 *
 * Referenced by:
 * - enrichmentQueue.jobId (one-to-many)
 */
export const enrichmentJobs = pgTable(
  "enrichment_jobs",
  {
    id: serial("id").primaryKey(),
    status: text("status").notNull().default("pending"), // pending, processing, completed, failed, cancelled
    filter: text("filter").default("all"), // all, unenriched
    batchSize: integer("batch_size").default(10),
    totalResources: integer("total_resources").default(0),
    processedResources: integer("processed_resources").default(0),
    successfulResources: integer("successful_resources").default(0),
    failedResources: integer("failed_resources").default(0),
    skippedResources: integer("skipped_resources").default(0),
    processedResourceIds: jsonb("processed_resource_ids").$type<number[]>().default([]),
    failedResourceIds: jsonb("failed_resource_ids").$type<number[]>().default([]),
    errorMessage: text("error_message"),
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    startedBy: varchar("started_by").references(() => users.id),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    index("idx_enrichment_jobs_status").on(table.status),
    index("idx_enrichment_jobs_started_by").on(table.startedBy),
  ]
);

export const insertEnrichmentJobSchema = createInsertSchema(enrichmentJobs).pick({
  filter: true,
  batchSize: true,
  startedBy: true,
});

export type InsertEnrichmentJob = z.infer<typeof insertEnrichmentJobSchema>;
export type EnrichmentJob = typeof enrichmentJobs.$inferSelect;

/**
 * Enrichment Queue table - Individual resource enrichment tasks
 *
 * Tracks individual resource enrichment tasks within a batch job.
 * Each queue item represents one resource to be analyzed by Claude AI with retry logic.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {number} jobId - Parent enrichment job (required, cascades on delete)
 * @property {number} resourceId - Resource to enrich (required, cascades on delete)
 * @property {string} status - Task status: 'pending', 'processing', 'completed', 'failed', 'skipped' (default: 'pending')
 * @property {number} retryCount - Number of retry attempts made (default: 0)
 * @property {number} maxRetries - Maximum retry attempts allowed (default: 3)
 * @property {string} errorMessage - Error details if enrichment failed
 * @property {object} aiMetadata - Claude AI-generated metadata (suggested title, description, tags, category, subcategory, confidence, key topics)
 * @property {timestamp} processedAt - When enrichment completed or failed
 * @property {timestamp} createdAt - Queue item creation timestamp
 * @property {timestamp} updatedAt - Last status update timestamp
 *
 * Constraints:
 * - Cascades delete when parent job or resource is deleted
 *
 * Indexes:
 * - idx_enrichment_queue_job_id: Fast lookup of all tasks in a job
 * - idx_enrichment_queue_resource_id: Check enrichment status for a resource
 * - idx_enrichment_queue_status: Fast filtering by task status
 *
 * Relationships:
 * - References enrichmentJobs.id (many-to-one)
 * - References resources.id (many-to-one)
 */
export const enrichmentQueue = pgTable(
  "enrichment_queue",
  {
    id: serial("id").primaryKey(),
    jobId: integer("job_id").references(() => enrichmentJobs.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    status: text("status").notNull().default("pending"), // pending, processing, completed, failed, skipped
    retryCount: integer("retry_count").default(0),
    maxRetries: integer("max_retries").default(3),
    errorMessage: text("error_message"),
    aiMetadata: jsonb("ai_metadata").$type<{
      suggestedTitle?: string;
      suggestedDescription?: string;
      suggestedTags?: string[];
      suggestedCategory?: string;
      suggestedSubcategory?: string;
      confidence?: number;
      keyTopics?: string[];
    }>(),
    processedAt: timestamp("processed_at"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    index("idx_enrichment_queue_job_id").on(table.jobId),
    index("idx_enrichment_queue_resource_id").on(table.resourceId),
    index("idx_enrichment_queue_status").on(table.status),
  ]
);

export const insertEnrichmentQueueSchema = createInsertSchema(enrichmentQueue).pick({
  jobId: true,
  resourceId: true,
  status: true,
  retryCount: true,
  maxRetries: true,
});

export type InsertEnrichmentQueue = z.infer<typeof insertEnrichmentQueueSchema>;
export type EnrichmentQueueItem = typeof enrichmentQueue.$inferSelect;

export interface LinkHealthJob {
  id: number;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  totalLinks: number;
  checkedLinks: number;
  healthyLinks: number;
  brokenLinks: number;
  redirectLinks: number;
  timeoutLinks: number;
  errorMessage?: string;
  startedAt?: string;
  completedAt?: string;
  createdAt: string;
}

export interface LinkHealthCheck {
  id: number;
  resourceId: number;
  url: string;
  status: 'healthy' | 'broken' | 'timeout' | 'redirect' | 'dns_failure';
  httpStatus?: number;
  responseTime?: number;
  redirectUrl?: string;
  errorMessage?: string;
  consecutiveFailures: number;
  flaggedForReview: boolean;
  lastCheckedAt: string;
}
