import { sql } from 'drizzle-orm';
import { pgTable, text, serial, varchar, timestamp, integer, boolean, jsonb, index, uniqueIndex, uuid, primaryKey, unique, real, customType, check, foreignKey } from "drizzle-orm/pg-core";

/**
 * Postgres tsvector column type for full-text search (BUG-018).
 * drizzle-orm has no built-in tsvector type, so a customType is required
 * to mirror migrations/0029_search_fts.sql in shared/schema.ts (keeps the
 * migration-drift check honest).
 */
const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector";
  },
});
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { taxonomyNameSchema, slugSchema, journeyTitleSchema, journeyDescriptionSchema } from "./validation";
import {
  resourceFormatSchema,
  resourceProviderSchema,
  resourceSkillLevelSchema,
  type ResourceFormat,
  type ResourceProvider,
  type ResourceSkillLevel,
} from "./resourceFacets";
import type { BookmarkQueueStatus } from "./bookmarkCollections";
import type {
  DigestAttemptOutcome,
  DigestCadence,
  DigestChannel,
  DigestJobStatus,
  NotificationKind,
} from "./notifications";
import {
  type LearningFormat,
  type LearningGoal,
  type LearningSkillLevel,
  type LearningTimeCommitment,
  type OnboardingStatus,
} from "./onboarding";

/**
 * Session storage table for Replit Auth
 *
 * Stores HTTP session data for authenticated users using Passport.js and connect-pg-simple.
 * Sessions are automatically cleaned up after expiration.
 *
 * @property {string} sid - Session identifier (primary key), generated by express-session
 * @property {object} sess - Session data stored as JSON (user info, passport data, etc.)
 * @property {timestamp} expire - Session expiration timestamp, indexed for efficient cleanup
 *
 * Indexes:
 * - IDX_session_expire: On expire column for fast expiration queries
 */
export const sessions = pgTable(
  "sessions",
  {
    sid: varchar("sid").primaryKey(),
    sess: jsonb("sess").notNull(),
    expire: timestamp("expire").notNull(),
  },
  (table) => [index("IDX_session_expire").on(table.expire)],
);

/**
 * Users table for authentication and user management
 *
 * Supports both Replit OAuth and local authentication. Users can have different roles
 * for authorization (user, admin, moderator).
 *
 * @property {string} id - UUID primary key, auto-generated using gen_random_uuid()
 * @property {string} email - User email address, unique constraint for login
 * @property {string} password - Hashed password using bcrypt (only for local auth, null for OAuth)
 * @property {string} firstName - User's first name from profile
 * @property {string} lastName - User's last name from profile
 * @property {string} profileImageUrl - URL to user's profile picture (from OAuth or uploaded)
 * @property {string} role - User role: 'user' (default), 'admin', or 'moderator'
 * @property {timestamp} createdAt - Account creation timestamp
 * @property {timestamp} updatedAt - Last profile update timestamp
 *
 * Constraints:
 * - Email must be unique
 * - ID is auto-generated UUID
 *
 * Referenced by:
 * - resources.submittedBy, resources.approvedBy
 * - resourceEdits.submittedBy, resourceEdits.handledBy
 * - userFavorites.userId
 * - userBookmarks.userId
 * - userJourneyProgress.userId
 * - userPreferences.userId
 * - userInteractions.userId
 * - resourceAuditLog.performedBy
 * - githubSyncHistory.performedBy
 * - enrichmentJobs.startedBy
 */
export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  email: varchar("email").unique(),
  password: varchar("password"), // For local authentication (hashed with bcrypt)
  firstName: varchar("first_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  role: text("role").default("user"), // user, admin, moderator
  // Run22 BUG-020: private account/data-deletion channel. Set when the user
  // requests deletion from their Profile (authenticated, no public GitHub
  // issue needed); admins see and action the request privately. NULL = no
  // pending request.
  deletionRequestedAt: timestamp("deletion_requested_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export type UpsertUser = typeof users.$inferInsert;
export type User = typeof users.$inferSelect;

/**
 * API Keys table for programmatic API access
 *
 * Stores API keys for third-party integrations and programmatic access to resources.
 * Keys are hashed using SHA-256 before storage for security. Only the plaintext key is
 * shown once during creation.
 *
 * @property {string} id - UUID primary key, auto-generated using gen_random_uuid()
 * @property {string} userId - Reference to user who owns this API key (cascades on delete)
 * @property {string} key - SHA-256 hash of the API key (unique constraint)
 * @property {string} name - User-provided label/description for the key (e.g., "My IDE Extension")
 * @property {object} scopes - JSON array of permission scopes (e.g., ["read:resources", "read:tags"])
 * @property {timestamp} createdAt - When the API key was created
 * @property {timestamp} lastUsedAt - Last time the key was used for authentication (null if never used)
 * @property {timestamp} expiresAt - Optional expiration timestamp (null for non-expiring keys)
 * @property {timestamp} revokedAt - When the key was revoked (null if active)
 *
 * Constraints:
 * - Key must be unique (hashed value)
 * - userId cascades on delete (removes API keys when user deleted)
 *
 * Indexes:
 * - idx_api_keys_user_id: Fast lookup of keys by user
 * - idx_api_keys_key: Fast authentication lookups by hashed key
 * - idx_api_keys_expires_at: Efficient expiration cleanup queries
 *
 * Security Notes:
 * - Keys are hashed with SHA-256 before storage (deterministic, enables O(1) lookup;
 *   safe because raw keys carry 256 bits of entropy — nothing to brute-force)
 * - Plaintext key only returned once during creation
 * - Revoked keys (revokedAt != null) cannot be used
 * - Expired keys (expiresAt < now) cannot be used
 */
export const apiKeys = pgTable(
  "api_keys",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    key: varchar("key").notNull().unique(),
    name: varchar("name").notNull(),
    scopes: jsonb("scopes").$type<string[]>().default([]).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    lastUsedAt: timestamp("last_used_at"),
    expiresAt: timestamp("expires_at"),
    revokedAt: timestamp("revoked_at"),
  },
  (table) => [
    index("idx_api_keys_user_id").on(table.userId),
    index("idx_api_keys_key").on(table.key),
    index("idx_api_keys_expires_at").on(table.expiresAt),
  ]
);

export type InsertApiKey = typeof apiKeys.$inferInsert;
export type ApiKey = typeof apiKeys.$inferSelect;

/**
 * Password reset tokens for the self-service "forgot password" flow.
 *
 * Only the SHA-256 hash of the single-use token is stored (never the raw token,
 * which is emailed to the user) — same defense-in-depth pattern as api_keys.
 * A token is valid only while used_at IS NULL AND expires_at > now(); it is
 * atomically claimed (single UPDATE ... RETURNING) at redemption to close the
 * double-use race. Rows cascade-delete with the owning user.
 */
export const passwordResetTokens = pgTable(
  "password_reset_tokens",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    tokenHash: varchar("token_hash").notNull().unique(),
    expiresAt: timestamp("expires_at").notNull(),
    usedAt: timestamp("used_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("idx_password_reset_tokens_user_id").on(table.userId),
    index("idx_password_reset_tokens_expires_at").on(table.expiresAt),
  ]
);

export type InsertPasswordResetToken = typeof passwordResetTokens.$inferInsert;
export type PasswordResetToken = typeof passwordResetTokens.$inferSelect;

/**
 * Resources table - Core content entity
 *
 * Stores curated video resources with approval workflow and GitHub synchronization.
 * Supports 3-level categorization (category > subcategory > sub-subcategory).
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} title - Resource title/name (required)
 * @property {string} url - Resource URL, must be unique to prevent duplicates
 * @property {string} description - Resource description or summary (defaults to empty string)
 * @property {string} category - Top-level category (required, e.g., "Frameworks", "Languages")
 * @property {string} subcategory - Second-level category (optional)
 * @property {string} subSubcategory - Third-level category (optional)
 * @property {string} status - Contributor lifecycle status plus internal archive state
 * @property {string} submittedBy - User ID who submitted the resource (cascades on user delete)
 * @property {string} approvedBy - User ID who approved the resource
 * @property {timestamp} approvedAt - When the resource was approved
 * @property {boolean} githubSynced - Whether resource has been synced to GitHub (default: false)
 * @property {timestamp} lastSyncedAt - Last GitHub sync timestamp
 * @property {object} metadata - Flexible JSON metadata (AI enrichment data, tags, etc.)
 * @property {timestamp} createdAt - Resource creation timestamp
 * @property {timestamp} updatedAt - Last modification timestamp
 *
 * Constraints:
 * - URL must be unique (prevents duplicate resources)
 * - submittedBy cascades on delete (removes resources when user deleted)
 *
 * Indexes:
 * - idx_resources_status: Fast filtering by approval status
 * - idx_resources_status_category: Combined status + category queries
 * - idx_resources_category: Fast category browsing
 *
 * Referenced by:
 * - resourceEdits.resourceId
 * - resourceTags (many-to-many)
 * - journeySteps.resourceId
 * - userFavorites (many-to-many)
 * - userBookmarks (many-to-many)
 * - userInteractions.resourceId
 * - resourceAuditLog.resourceId
 * - enrichmentQueue.resourceId
 */
export const resources = pgTable(
  "resources",
  {
    id: serial("id").primaryKey(),
    title: text("title").notNull(),
    url: text("url").notNull().unique(), // BUG #4 FIX: Prevent duplicate URLs
    description: text("description").notNull().default(""),
    category: text("category").notNull(),
    subcategory: text("subcategory"),
    subSubcategory: text("sub_subcategory"),
    // Task #294: explicit, curated discovery facets. `unknown` is intentional:
    // it represents missing curation and must never be inferred at request time.
    resourceFormat: text("resource_format").$type<ResourceFormat>().notNull().default("unknown"),
    provider: text("provider").$type<ResourceProvider>().notNull().default("unknown"),
    skillLevel: text("skill_level").$type<ResourceSkillLevel>().notNull().default("unknown"),
    status: text("status").default("approved"), // pending, approved, rejected, withdrawn, archived
    submittedBy: varchar("submitted_by").references(() => users.id, { onDelete: "cascade" }),
    approvedBy: varchar("approved_by").references(() => users.id),
    approvedAt: timestamp("approved_at"),
    // Explicitly contributor-facing copy. Internal moderator notes remain in
    // resource_audit_log and are never serialized by the contributor API.
    contributorRejectionReason: text("contributor_rejection_reason"),
    // Durable lifecycle timestamp for contributor-facing status changes. This
    // is separate from updatedAt, which also changes for ordinary catalog edits.
    statusChangedAt: timestamp("status_changed_at"),
    githubSynced: boolean("github_synced").default(false),
    lastSyncedAt: timestamp("last_synced_at"),
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
    // BUG-018 (migrations/0029_search_fts.sql): generated tsvector for FTS.
    searchTsv: tsvector("search_tsv").generatedAlwaysAs(
      (): any =>
        sql`to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, '') || ' ' || coalesce(url, ''))`,
    ),
  },
  (table) => [
    index("idx_resources_status").on(table.status),
    index("idx_resources_status_category").on(table.status, table.category),
    index("idx_resources_category").on(table.category),
    index("idx_resources_submitted_by_status_created_at").on(
      table.submittedBy,
      table.status,
      table.createdAt,
    ),
    index("idx_resources_search_tsv").using("gin", table.searchTsv),
    // Public search always gates on approved status. Partial indexes keep the
    // facet indexes small and match that hot query predicate.
    index("idx_resources_approved_format").on(table.resourceFormat).where(sql`${table.status} = 'approved'`),
    index("idx_resources_approved_provider").on(table.provider).where(sql`${table.status} = 'approved'`),
    index("idx_resources_approved_skill_level").on(table.skillLevel).where(sql`${table.status} = 'approved'`),
    // Schema DDL cannot contain bind parameters. Keep these literals in
    // lockstep with shared/resourceFacets.ts and migration 0040.
    check("resources_resource_format_check", sql`${table.resourceFormat} IN ('unknown','tool','library','player','sdk','api-service','platform','course','article','video','book','specification','dataset','community','other')`),
    check("resources_provider_check", sql`${table.provider} IN ('unknown','self-hosted','github','youtube','vimeo','aws','google-cloud','azure','cloudflare','mux','akamai','wowza','brightcove','bitmovin','other')`),
    check("resources_skill_level_check", sql`${table.skillLevel} IN ('unknown','beginner','intermediate','advanced','all-levels')`),
  ]
);

export const insertResourceSchema = createInsertSchema(resources).pick({
  title: true,
  url: true,
  description: true,
  category: true,
  subcategory: true,
  subSubcategory: true,
  resourceFormat: true,
  provider: true,
  skillLevel: true,
  status: true,
  submittedBy: true,
  metadata: true,
}).extend({
  resourceFormat: resourceFormatSchema.optional(),
  provider: resourceProviderSchema.optional(),
  skillLevel: resourceSkillLevelSchema.optional(),
});

export type InsertResource = z.infer<typeof insertResourceSchema>;
export type Resource = typeof resources.$inferSelect;

/**
 * Resource Edits table - Crowdsourced edit suggestions
 *
 * Implements a suggest-edit workflow allowing users to propose changes to existing resources.
 * Includes AI-powered analysis via Claude for quality suggestions.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {number} resourceId - Reference to the resource being edited (required)
 * @property {string} submittedBy - User who submitted the edit suggestion (required)
 * @property {string} status - Edit status: pending, approved, rejected, withdrawn, or superseded
 * @property {timestamp} originalResourceUpdatedAt - Timestamp of resource when edit was created (for conflict detection)
 * @property {object} proposedChanges - Field-by-field changes showing old vs new values
 * @property {object} proposedData - Complete proposed resource data after changes applied
 * @property {object} claudeMetadata - AI-generated suggestions and analysis (title, description, tags, category, confidence, topics)
 * @property {timestamp} claudeAnalyzedAt - When Claude analyzed the edit suggestion
 * @property {string} handledBy - Admin/moderator who approved or rejected the edit
 * @property {timestamp} handledAt - When the edit was approved or rejected
 * @property {string} rejectionReason - Explanation if edit was rejected
 * @property {timestamp} createdAt - Edit suggestion creation timestamp
 * @property {timestamp} updatedAt - Last modification timestamp
 *
 * Indexes:
 * - idx_resource_edits_resource_id: Fast lookup of edits for a specific resource
 * - idx_resource_edits_status: Filter pending/approved/rejected edits
 * - idx_resource_edits_submitted_by: Track edits by user
 *
 * Relationships:
 * - References resources.id (the resource being edited)
 * - References users.id for submittedBy and handledBy
 */
export const resourceEdits = pgTable(
  "resource_edits",
  {
    id: serial("id").primaryKey(),
    resourceId: integer("resource_id").references(() => resources.id).notNull(),
    submittedBy: varchar("submitted_by").references(() => users.id).notNull(),
    status: text("status")
      .$type<"pending" | "approved" | "rejected" | "withdrawn" | "superseded">()
      .default("pending")
      .notNull(),

    originalResourceUpdatedAt: timestamp("original_resource_updated_at").notNull(),

    proposedChanges: jsonb("proposed_changes").$type<Record<string, { old: any; new: any }>>().notNull(),
    proposedData: jsonb("proposed_data").$type<Partial<Resource>>().notNull(),

    claudeMetadata: jsonb("claude_metadata").$type<{
      suggestedTitle?: string;
      suggestedDescription?: string;
      suggestedTags?: string[];
      suggestedCategory?: string;
      suggestedSubcategory?: string;
      suggestedSubSubcategory?: string;
      confidence?: number;
      keyTopics?: string[];
    }>(),
    claudeAnalyzedAt: timestamp("claude_analyzed_at"),

    handledBy: varchar("handled_by").references(() => users.id),
    handledAt: timestamp("handled_at"),
    withdrawnAt: timestamp("withdrawn_at"),
    rejectionReason: text("rejection_reason"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("idx_resource_edits_resource_id").on(table.resourceId),
    index("idx_resource_edits_status").on(table.status),
    index("idx_resource_edits_submitted_by").on(table.submittedBy),
    index("idx_resource_edits_submitted_by_status_created_at").on(
      table.submittedBy,
      table.status,
      table.createdAt,
    ),
  ]
);

export const insertResourceEditSchema = createInsertSchema(resourceEdits).pick({
  resourceId: true,
  submittedBy: true,
  status: true,
  originalResourceUpdatedAt: true,
  proposedChanges: true,
  proposedData: true,
  claudeMetadata: true,
  claudeAnalyzedAt: true,
});

export type InsertResourceEdit = z.infer<typeof insertResourceEditSchema>;
export type ResourceEdit = typeof resourceEdits.$inferSelect;

/**
 * Categories table - Top-level taxonomy
 *
 * Defines the primary categorization for resources (e.g., "Frameworks", "Languages", "Tools").
 * Forms the root of a 3-level hierarchy: category > subcategory > sub-subcategory.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} name - Display name of the category (required, unique)
 * @property {string} slug - URL-friendly identifier (required, unique, used in routing)
 *
 * Constraints:
 * - Both name and slug must be unique
 *
 * Referenced by:
 * - subcategories.categoryId (one-to-many)
 */
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  slug: text("slug").notNull().unique(),
});

// R5-002 (run24): drizzle-zod only enforces column TYPES — <script> names,
// bidi-only names, 300-char names and '../evil' slugs all persisted. Every
// taxonomy write now routes through the shared content rules.
export const insertCategorySchema = createInsertSchema(categories).pick({
  name: true,
  slug: true,
}).extend({
  name: taxonomyNameSchema,
  slug: slugSchema,
});

export const updateCategorySchema = insertCategorySchema.partial();

export type InsertCategory = z.infer<typeof insertCategorySchema>;
export type UpdateCategory = z.infer<typeof updateCategorySchema>;
export type Category = typeof categories.$inferSelect;

/**
 * Subcategories table - Second-level taxonomy
 *
 * Defines subcategories within a parent category (e.g., "React" under "Frameworks").
 * Part of a 3-level hierarchy: category > subcategory > sub-subcategory.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} name - Display name of the subcategory (required)
 * @property {string} slug - URL-friendly identifier (required)
 * @property {number} categoryId - Parent category reference (cascades on delete)
 *
 * Constraints:
 * - Unique constraint on (slug, categoryId) to prevent duplicate subcategories within same category
 * - Cascades delete when parent category is deleted
 *
 * Relationships:
 * - References categories.id (many-to-one)
 *
 * Referenced by:
 * - subSubcategories.subcategoryId (one-to-many)
 */
export const subcategories = pgTable("subcategories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  categoryId: integer("category_id").references(() => categories.id, { onDelete: "cascade" }),
}, (table) => [
  // BUG #3 FIX: Prevent duplicate subcategories within same category
  unique("subcategories_slug_category_unique").on(table.slug, table.categoryId),
]);

export const insertSubcategorySchema = createInsertSchema(subcategories).pick({
  name: true,
  slug: true,
  categoryId: true,
}).extend({
  // R5-002: same shared content rules as categories.
  name: taxonomyNameSchema,
  slug: slugSchema,
});

export const updateSubcategorySchema = insertSubcategorySchema.partial();

export type InsertSubcategory = z.infer<typeof insertSubcategorySchema>;
export type UpdateSubcategory = z.infer<typeof updateSubcategorySchema>;
export type Subcategory = typeof subcategories.$inferSelect;

/**
 * Sub-subcategories table - Third-level taxonomy
 *
 * Defines the most granular categorization level (e.g., "Hooks" under "React" under "Frameworks").
 * Completes the 3-level hierarchy: category > subcategory > sub-subcategory.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} name - Display name of the sub-subcategory (required)
 * @property {string} slug - URL-friendly identifier (required)
 * @property {number} subcategoryId - Parent subcategory reference (cascades on delete)
 *
 * Constraints:
 * - Unique constraint on (slug, subcategoryId) to prevent duplicate sub-subcategories within same subcategory
 * - Cascades delete when parent subcategory is deleted
 *
 * Relationships:
 * - References subcategories.id (many-to-one)
 */
export const subSubcategories = pgTable("sub_subcategories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  subcategoryId: integer("subcategory_id").references(() => subcategories.id, { onDelete: "cascade" }),
}, (table) => [
  // Prevent duplicate sub-subcategories within same subcategory
  unique("sub_subcategories_slug_subcategory_unique").on(table.slug, table.subcategoryId),
]);

export const insertSubSubcategorySchema = createInsertSchema(subSubcategories).pick({
  name: true,
  slug: true,
  subcategoryId: true,
}).extend({
  // R5-002: same shared content rules as categories.
  name: taxonomyNameSchema,
  slug: slugSchema,
});

export const updateSubSubcategorySchema = insertSubSubcategorySchema.partial();

export type InsertSubSubcategory = z.infer<typeof insertSubSubcategorySchema>;
export type UpdateSubSubcategory = z.infer<typeof updateSubSubcategorySchema>;
export type SubSubcategory = typeof subSubcategories.$inferSelect;

/**
 * Awesome Lists table - External curated lists
 *
 * Stores references to external "Awesome List" repositories for importing resources.
 * Enables bulk import from community-curated awesome-* GitHub repositories.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} title - Name of the awesome list (required)
 * @property {string} description - Description of the list's focus and content (defaults to empty string)
 * @property {string} repoUrl - GitHub repository URL (required, e.g., "https://github.com/sindresorhus/awesome")
 * @property {string} sourceUrl - Direct URL to the raw markdown file for parsing (required)
 */
export const awesomeLists = pgTable("awesome_lists", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  repoUrl: text("repo_url").notNull(),
  sourceUrl: text("source_url").notNull(),
});

export const insertAwesomeListSchema = createInsertSchema(awesomeLists).pick({
  title: true,
  description: true,
  repoUrl: true,
  sourceUrl: true,
});

export type InsertAwesomeList = z.infer<typeof insertAwesomeListSchema>;
export type AwesomeList = typeof awesomeLists.$inferSelect;

/**
 * Tags table - Flexible resource labeling
 *
 * Stores tags for cross-cutting resource organization beyond hierarchical categories.
 * Tags enable discovery via topics like "tutorial", "beginner-friendly", "video", etc.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} name - Display name of the tag (required, unique)
 * @property {string} slug - URL-friendly identifier (required, unique)
 * @property {timestamp} createdAt - Tag creation timestamp
 *
 * Constraints:
 * - Both name and slug must be unique
 *
 * Referenced by:
 * - resourceTags (many-to-many with resources)
 */
export const tags = pgTable("tags", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  slug: text("slug").notNull().unique(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertTagSchema = createInsertSchema(tags).pick({
  name: true,
  slug: true,
});

export type InsertTag = z.infer<typeof insertTagSchema>;
export type Tag = typeof tags.$inferSelect;

/**
 * Resource Tags junction table - Many-to-many relationship
 *
 * Links resources to tags, enabling flexible multi-tag categorization.
 * One resource can have many tags, and one tag can apply to many resources.
 *
 * @property {number} resourceId - Reference to the resource (required, cascades on delete)
 * @property {number} tagId - Reference to the tag (required, cascades on delete)
 *
 * Constraints:
 * - Composite primary key on (resourceId, tagId) prevents duplicate tag assignments
 * - Both foreign keys cascade delete (removing resource or tag removes the association)
 *
 * Relationships:
 * - References resources.id (many-to-many)
 * - References tags.id (many-to-many)
 */
export const resourceTags = pgTable(
  "resource_tags",
  {
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    tagId: integer("tag_id").references(() => tags.id, { onDelete: "cascade" }).notNull(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.resourceId, table.tagId] }),
  })
);

/**
 * Learning Journeys table - Structured learning paths
 *
 * Curated sequences of resources forming guided learning paths.
 * Helps users follow a structured curriculum from beginner to advanced topics.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} title - Journey title/name (required, e.g., "React Fundamentals")
 * @property {string} description - Detailed description of learning objectives and outcomes (required)
 * @property {string} difficulty - Skill level: 'beginner', 'intermediate', or 'advanced' (default: 'beginner')
 * @property {string} estimatedDuration - Human-readable time estimate (e.g., "20 hours", "3 weeks")
 * @property {string} icon - Icon identifier for visual representation
 * @property {number} orderIndex - Sort order for displaying journeys
 * @property {string} category - Primary category this journey belongs to (required)
 * @property {string} status - Publication status: 'draft', 'published', or 'archived' (default: 'published')
 * @property {timestamp} createdAt - Journey creation timestamp
 * @property {timestamp} updatedAt - Last modification timestamp
 *
 * Referenced by:
 * - journeySteps (one-to-many)
 * - userJourneyProgress (one-to-many)
 */
export const learningJourneys = pgTable("learning_journeys", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  difficulty: text("difficulty").default("beginner"), // beginner, intermediate, advanced
  estimatedDuration: text("estimated_duration"), // e.g., "20 hours"
  icon: text("icon"),
  orderIndex: integer("order_index"),
  category: text("category").notNull(),
  status: text("status").default("published"), // draft, published, archived
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// R5-002 (run24): journey title/description now share the same content rules
// as the rest of the catalog (visible chars required, length caps, no HTML,
// no control chars) instead of accepting any text() value.
export const insertLearningJourneySchema = createInsertSchema(learningJourneys).pick({
  title: true,
  description: true,
  difficulty: true,
  estimatedDuration: true,
  icon: true,
  orderIndex: true,
  category: true,
  status: true,
}).extend({
  title: journeyTitleSchema,
  description: journeyDescriptionSchema,
});

export type InsertLearningJourney = z.infer<typeof insertLearningJourneySchema>;
export type LearningJourney = typeof learningJourneys.$inferSelect;

/**
 * Journey Steps table - Individual learning path steps
 *
 * Defines ordered steps within a learning journey, each optionally linked to a resource.
 * Steps can be mandatory or optional, enabling flexible learning paths.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {number} journeyId - Parent learning journey (required, cascades on delete)
 * @property {number} resourceId - Associated resource for this step (optional, cascades on delete)
 * @property {number} stepNumber - Order within the journey (required, determines sequence)
 * @property {string} title - Step title/name (required)
 * @property {string} description - Step description, learning objectives, or instructions
 * @property {boolean} isOptional - Whether this step can be skipped (default: false)
 * @property {timestamp} createdAt - Step creation timestamp
 *
 * Constraints:
 * - Cascades delete when parent journey or linked resource is deleted
 *
 * Indexes:
 * - idx_journey_steps_journey_id: Fast lookup of all steps in a journey
 * - idx_journey_steps_resource_id: Find journeys using a specific resource
 *
 * Relationships:
 * - References learningJourneys.id (many-to-one)
 * - References resources.id (many-to-one, optional)
 *
 * Referenced by:
 * - userJourneyProgress.currentStepId
 */
export const journeySteps = pgTable(
  "journey_steps",
  {
    id: serial("id").primaryKey(),
    journeyId: integer("journey_id").references(() => learningJourneys.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }),
    stepNumber: integer("step_number").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    isOptional: boolean("is_optional").default(false),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("idx_journey_steps_journey_id").on(table.journeyId),
    index("idx_journey_steps_resource_id").on(table.resourceId),
  ]
);

export const insertJourneyStepSchema = createInsertSchema(journeySteps).pick({
  journeyId: true,
  resourceId: true,
  stepNumber: true,
  title: true,
  description: true,
  isOptional: true,
});

export type InsertJourneyStep = z.infer<typeof insertJourneyStepSchema>;
export type JourneyStep = typeof journeySteps.$inferSelect;

/**
 * User Favorites junction table - Many-to-many relationship
 *
 * Tracks which resources users have marked as favorites for quick access.
 * Enables personalized resource collections.
 *
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {number} resourceId - Reference to the favorited resource (required, cascades on delete)
 * @property {timestamp} createdAt - When the resource was favorited
 *
 * Constraints:
 * - Composite primary key on (userId, resourceId) prevents duplicate favorites
 * - Both foreign keys cascade delete (removing user or resource removes the favorite)
 *
 * Relationships:
 * - References users.id (many-to-many)
 * - References resources.id (many-to-many)
 */
export const userFavorites = pgTable(
  "user_favorites",
  {
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.userId, table.resourceId] }),
  })
);

/**
 * User Bookmarks junction table - Many-to-many relationship with notes
 *
 * Tracks bookmarked resources with optional personal notes.
 * Similar to favorites but allows users to add context and reminders.
 *
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {number} resourceId - Reference to the bookmarked resource (required, cascades on delete)
 * @property {string} notes - User's personal notes about the resource (optional)
 * @property {timestamp} createdAt - When the bookmark was created
 *
 * Constraints:
 * - Composite primary key on (userId, resourceId) prevents duplicate bookmarks
 * - Both foreign keys cascade delete (removing user or resource removes the bookmark)
 *
 * Relationships:
 * - References users.id (many-to-many)
 * - References resources.id (many-to-many)
 */
export const userBookmarks = pgTable(
  "user_bookmarks",
  {
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    notes: text("notes"),
    queueStatus: text("queue_status").$type<BookmarkQueueStatus>().notNull().default("saved"),
    archivedAt: timestamp("archived_at"),
    personalTags: jsonb("personal_tags").$type<string[]>().notNull().default([]),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.userId, table.resourceId] }),
    check(
      "user_bookmarks_queue_status_check",
      sql`${table.queueStatus} IN ('saved','watch-next','in-progress','done')`,
    ),
    check(
      "user_bookmarks_personal_tags_array_check",
      sql`jsonb_typeof(${table.personalTags}) = 'array'`,
    ),
    index("idx_user_bookmarks_queue").on(table.userId, table.queueStatus, table.archivedAt),
  ]
);

export type UserBookmark = typeof userBookmarks.$inferSelect;

/**
 * User-owned bookmark collections. Collections organize user_bookmarks without
 * replacing them; deleting a collection only cascades its membership rows.
 */
export const bookmarkCollections = pgTable(
  "bookmark_collections",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    name: text("name").notNull(),
    position: integer("position").notNull().default(0),
    archivedAt: timestamp("archived_at"),
    shareId: text("share_id"),
    publishedAt: timestamp("published_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    unique("bookmark_collections_id_user_unique").on(table.id, table.userId),
    uniqueIndex("bookmark_collections_share_id_unique").on(table.shareId),
    index("idx_bookmark_collections_owner_order").on(table.userId, table.archivedAt, table.position, table.id),
  ],
);

export type BookmarkCollection = typeof bookmarkCollections.$inferSelect;
export type InsertBookmarkCollection = typeof bookmarkCollections.$inferInsert;

/**
 * Collection memberships are anchored to the owner's existing bookmark row.
 * Composite foreign keys enforce same-owner collection/bookmark membership.
 */
export const bookmarkCollectionItems = pgTable(
  "bookmark_collection_items",
  {
    collectionId: integer("collection_id").notNull(),
    userId: varchar("user_id").notNull(),
    resourceId: integer("resource_id").notNull(),
    position: integer("position").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.collectionId, table.resourceId] }),
    foreignKey({
      name: "bookmark_collection_items_collection_owner_fk",
      columns: [table.collectionId, table.userId],
      foreignColumns: [bookmarkCollections.id, bookmarkCollections.userId],
    }).onDelete("cascade"),
    foreignKey({
      name: "bookmark_collection_items_bookmark_owner_fk",
      columns: [table.userId, table.resourceId],
      foreignColumns: [userBookmarks.userId, userBookmarks.resourceId],
    }).onDelete("cascade"),
    index("idx_bookmark_collection_items_owner_resource").on(table.userId, table.resourceId),
    index("idx_bookmark_collection_items_order").on(table.collectionId, table.position, table.resourceId),
  ],
);

export type BookmarkCollectionItem = typeof bookmarkCollectionItems.$inferSelect;
export type InsertBookmarkCollectionItem = typeof bookmarkCollectionItems.$inferInsert;

/**
 * User Journey Progress table - Learning path tracking
 *
 * Tracks each user's progress through learning journeys, including completed steps
 * and current position. Enables resume functionality and progress analytics.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {number} journeyId - Reference to the learning journey (required, cascades on delete)
 * @property {number} currentStepId - Current step user is on (optional reference to journeySteps)
 * @property {number[]} completedSteps - Array of completed step IDs (default: empty array)
 * @property {timestamp} startedAt - When user started this journey
 * @property {timestamp} lastAccessedAt - Last time user accessed this journey
 * @property {timestamp} completedAt - When user completed all steps (null if incomplete)
 *
 * Constraints:
 * - Unique constraint on (userId, journeyId) - one progress record per user per journey
 * - Cascades delete when user or journey is deleted
 *
 * Indexes:
 * - idx_user_journey_progress_user_id: Find all journeys for a user
 * - idx_user_journey_progress_journey_id: Find all users in a journey
 *
 * Relationships:
 * - References users.id (many-to-one)
 * - References learningJourneys.id (many-to-one)
 * - References journeySteps.id for currentStepId (many-to-one, optional)
 */
export const userJourneyProgress = pgTable(
  "user_journey_progress",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    journeyId: integer("journey_id").references(() => learningJourneys.id, { onDelete: "cascade" }).notNull(),
    currentStepId: integer("current_step_id").references(() => journeySteps.id),
    completedSteps: jsonb("completed_steps").$type<number[]>().default([]),
    startedAt: timestamp("started_at").defaultNow(),
    lastAccessedAt: timestamp("last_accessed_at").defaultNow(),
    completedAt: timestamp("completed_at"),
  },
  (table) => [
    unique("user_journey_unique").on(table.userId, table.journeyId),
    index("idx_user_journey_progress_user_id").on(table.userId),
    index("idx_user_journey_progress_journey_id").on(table.journeyId),
  ]
);

export const insertUserJourneyProgressSchema = createInsertSchema(userJourneyProgress).pick({
  userId: true,
  journeyId: true,
  currentStepId: true,
  completedSteps: true,
});

export type InsertUserJourneyProgress = z.infer<typeof insertUserJourneyProgressSchema>;
export type UserJourneyProgress = typeof userJourneyProgress.$inferSelect;

/**
 * Resource Audit Log table - Change history tracking
 *
 * Maintains a complete audit trail of all resource modifications for compliance,
 * debugging, and analytics. Preserves history even after resource deletion.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {number} resourceId - Current resource reference (nullable, SET NULL on resource delete)
 * @property {number} originalResourceId - Original resource ID, never nullified (preserves history after deletion)
 * @property {string} action - Action type: 'created', 'updated', 'approved', 'rejected', 'synced', 'deleted' (required)
 * @property {string} performedBy - User who performed the action (nullable, SET NULL on user delete)
 * @property {object} changes - JSON object containing changed fields and values
 * @property {string} notes - Optional notes or comments about the change
 * @property {timestamp} createdAt - When the action occurred
 *
 * Constraints:
 * - resourceId uses SET NULL on delete (maintains audit log after resource deletion)
 * - performedBy uses SET NULL on delete (maintains audit log after user deletion)
 * - originalResourceId never changes (preserves original resource ID for historical reference)
 *
 * Relationships:
 * - References resources.id (many-to-one, nullable)
 * - References users.id for performedBy (many-to-one, nullable)
 */
export const resourceAuditLog = pgTable("resource_audit_log", {
  id: serial("id").primaryKey(),
  resourceId: integer("resource_id").references(() => resources.id, { onDelete: "set null" }),
  originalResourceId: integer("original_resource_id"), // Never SET NULL - preserves history after deletion
  action: text("action").notNull(), // created, updated, approved, rejected, synced, deleted
  performedBy: varchar("performed_by").references(() => users.id, { onDelete: "set null" }),
  changes: jsonb("changes").$type<Record<string, any>>(),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
});

/**
 * GitHub Sync Queue table - Async GitHub operations
 *
 * Queues GitHub import/export operations for async processing.
 * Enables batch synchronization between database and GitHub repositories.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} repositoryUrl - Target GitHub repository URL (required)
 * @property {string} branch - Target branch name (default: 'main')
 * @property {number[]} resourceIds - Array of resource IDs to sync (default: empty array)
 * @property {string} action - Operation type: 'import' or 'export' (required)
 * @property {string} status - Queue status: 'pending', 'processing', 'completed', or 'failed' (default: 'pending')
 * @property {string} errorMessage - Error details if status is 'failed'
 * @property {object} metadata - Additional sync metadata (default: empty object)
 * @property {timestamp} createdAt - When sync was queued
 * @property {timestamp} processedAt - When sync completed or failed
 *
 * Indexes:
 * - idx_github_sync_queue_status: Fast filtering by status for queue processing
 */
export const githubSyncQueue = pgTable(
  "github_sync_queue",
  {
    id: serial("id").primaryKey(),
    repositoryUrl: text("repository_url").notNull(),
    branch: text("branch").default("main"),
    resourceIds: jsonb("resource_ids").$type<number[]>().default([]),
    action: text("action").notNull(), // import, export
    status: text("status").default("pending"), // pending, processing, completed, failed
    errorMessage: text("error_message"),
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    createdAt: timestamp("created_at").defaultNow(),
    processedAt: timestamp("processed_at"),
  },
  (table) => [
    index("idx_github_sync_queue_status").on(table.status),
  ]
);

export const insertGithubSyncQueueSchema = createInsertSchema(githubSyncQueue).pick({
  repositoryUrl: true,
  branch: true,
  resourceIds: true,
  action: true,
  status: true,
  metadata: true,
});

export type InsertGithubSyncQueue = z.infer<typeof insertGithubSyncQueueSchema>;
export type GithubSyncQueue = typeof githubSyncQueue.$inferSelect;

/**
 * User Preferences table - Personalization settings
 *
 * Stores user preferences for personalized recommendations and content filtering.
 * Enables AI-powered recommendation engine to tailor results to user interests.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {string[]} preferredCategories - Array of preferred category names (default: empty array)
 * @property {string} skillLevel - Self-reported skill: 'beginner', 'intermediate', or 'advanced' (default: 'beginner')
 * @property {string[]} learningGoals - Array of learning objectives (default: empty array)
 * @property {string[]} preferredResourceTypes - Array of preferred content types (default: empty array)
 * @property {string} timeCommitment - Learning frequency: 'daily', 'weekly', or 'flexible' (default: 'flexible')
 * @property {timestamp} createdAt - Preferences creation timestamp
 * @property {timestamp} updatedAt - Last modification timestamp
 *
 * Constraints:
 * - Unique constraint on userId (one preferences record per user)
 * - Cascades delete when user is deleted
 *
 * Indexes:
 * - idx_user_preferences_user_id: Fast user preference lookup
 *
 * Relationships:
 * - References users.id (one-to-one)
 */
export const userPreferences = pgTable(
  "user_preferences",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    preferredCategories: jsonb("preferred_categories").$type<string[]>().default([]).notNull(),
    skillLevel: text("skill_level").$type<LearningSkillLevel>().notNull().default("beginner"),
    learningGoals: jsonb("learning_goals").$type<LearningGoal[]>().default([]).notNull(),
    preferredResourceTypes: jsonb("preferred_resource_types").$type<LearningFormat[]>().default([]).notNull(),
    timeCommitment: text("time_commitment").$type<LearningTimeCommitment>().default("flexible").notNull(),
    onboardingStatus: text("onboarding_status").$type<OnboardingStatus>().default("not_started").notNull(),
    onboardingStep: integer("onboarding_step").default(1).notNull(),
    onboardingCompletedAt: timestamp("onboarding_completed_at"),
    onboardingDismissedAt: timestamp("onboarding_dismissed_at"),
    revision: integer("revision").default(1).notNull(),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    index("idx_user_preferences_user_id").on(table.userId),
    unique("user_preferences_user_id_unique").on(table.userId),
    check("user_preferences_skill_level_check", sql`${table.skillLevel} IN ('beginner','intermediate','advanced')`),
    check("user_preferences_time_commitment_check", sql`${table.timeCommitment} IN ('daily','weekly','flexible')`),
    check("user_preferences_onboarding_status_check", sql`${table.onboardingStatus} IN ('not_started','in_progress','completed','dismissed')`),
    check("user_preferences_onboarding_step_check", sql`${table.onboardingStep} BETWEEN 1 AND 5`),
    check("user_preferences_revision_check", sql`${table.revision} >= 1`),
    check("user_preferences_learning_goals_values_check", sql`${table.learningGoals} <@ '["learn-fundamentals","build-video-apps","improve-streaming","optimize-encoding","operate-infrastructure","keep-current"]'::jsonb`),
    check("user_preferences_resource_types_values_check", sql`${table.preferredResourceTypes} <@ '["video","course","article","book","specification","tool","library","community"]'::jsonb`),
  ]
);

export const insertUserPreferencesSchema = createInsertSchema(userPreferences).pick({
  userId: true,
  preferredCategories: true,
  skillLevel: true,
  learningGoals: true,
  preferredResourceTypes: true,
  timeCommitment: true,
  onboardingStatus: true,
  onboardingStep: true,
  onboardingCompletedAt: true,
  onboardingDismissedAt: true,
});

export type InsertUserPreferences = z.infer<typeof insertUserPreferencesSchema>;
export type UserPreferences = typeof userPreferences.$inferSelect;

/**
 * Explicit reminder consent and delivery policy. Email and in-app consent are
 * independent and default off. The raw email-unsubscribe token is never stored.
 */
export const notificationPreferences = pgTable(
  "notification_preferences",
  {
    userId: varchar("user_id")
      .primaryKey()
      .references(() => users.id, { onDelete: "cascade" }),
    emailDigestEnabled: boolean("email_digest_enabled").notNull().default(false),
    inAppEnabled: boolean("in_app_enabled").notNull().default(false),
    includeNewResources: boolean("include_new_resources").notNull().default(true),
    includeWatchNext: boolean("include_watch_next").notNull().default(true),
    includeJourneyStep: boolean("include_journey_step").notNull().default(true),
    cadence: text("cadence").$type<DigestCadence>().notNull().default("weekly"),
    timezone: varchar("timezone", { length: 64 }).notNull().default("UTC"),
    policyVersion: integer("policy_version").notNull().default(1),
    pausedUntil: timestamp("paused_until", { withTimezone: true }),
    emailOptedInAt: timestamp("email_opted_in_at", { withTimezone: true }),
    emailUnsubscribedAt: timestamp("email_unsubscribed_at", { withTimezone: true }),
    inAppOptedInAt: timestamp("in_app_opted_in_at", { withTimezone: true }),
    lastEmailDigestAt: timestamp("last_email_digest_at", { withTimezone: true }),
    lastInAppDigestAt: timestamp("last_in_app_digest_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("idx_notification_preferences_email_due")
      .on(table.emailDigestEnabled, table.pausedUntil, table.lastEmailDigestAt),
    index("idx_notification_preferences_in_app_due")
      .on(table.inAppEnabled, table.pausedUntil, table.lastInAppDigestAt),
    check(
      "notification_preferences_cadence_check",
      sql`${table.cadence} IN ('weekly','biweekly','monthly')`,
    ),
    check(
      "notification_preferences_policy_version_check",
      sql`${table.policyVersion} >= 1`,
    ),
  ],
);

export type NotificationPreferences = typeof notificationPreferences.$inferSelect;

/**
 * Long-lived, single-use unsubscribe links. Each digest receives its own random
 * token, while only the SHA-256 hash is retained at rest.
 */
export const digestUnsubscribeTokens = pgTable(
  "digest_unsubscribe_tokens",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("idx_digest_unsubscribe_tokens_user").on(table.userId),
    index("idx_digest_unsubscribe_tokens_expires").on(table.expiresAt),
  ],
);

export type DigestUnsubscribeToken =
  typeof digestUnsubscribeTokens.$inferSelect;

/**
 * Minimal in-app reminder payloads. Hrefs are app-owned paths only; private
 * notes, external resource URLs, and behavioral history never enter this table.
 */
export const inAppNotifications = pgTable(
  "in_app_notifications",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    kind: text("kind").$type<NotificationKind>().notNull(),
    title: text("title").notNull(),
    description: text("description").notNull(),
    href: text("href").notNull(),
    resourceId: integer("resource_id").references(() => resources.id, {
      onDelete: "set null",
    }),
    collectionId: integer("collection_id").references(
      () => bookmarkCollections.id,
      { onDelete: "set null" },
    ),
    journeyId: integer("journey_id").references(() => learningJourneys.id, {
      onDelete: "set null",
    }),
    stepNumber: integer("step_number"),
    idempotencyKey: text("idempotency_key").notNull().unique(),
    readAt: timestamp("read_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("idx_in_app_notifications_user_created").on(
      table.userId,
      table.createdAt,
    ),
    index("idx_in_app_notifications_user_read").on(
      table.userId,
      table.readAt,
      table.createdAt,
    ),
    index("idx_in_app_notifications_expires_at").on(table.expiresAt),
    check(
      "in_app_notifications_kind_check",
      sql`${table.kind} IN ('new_resource','watch_next','journey_step')`,
    ),
    check(
      "in_app_notifications_href_check",
      sql`${table.href} ~ '^/(resource|bookmarks|journey)/'`,
    ),
  ],
);

export type InAppNotification = typeof inAppNotifications.$inferSelect;

/**
 * Durable, idempotent digest outbox. No message content or unsubscribe token is
 * stored in a job; content is selected from the owning user's current data.
 */
export const digestJobs = pgTable(
  "digest_jobs",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    channel: text("channel").$type<DigestChannel>().notNull(),
    periodKey: varchar("period_key", { length: 96 }).notNull(),
    policyVersion: integer("policy_version").notNull().default(1),
    idempotencyKey: text("idempotency_key").notNull().unique(),
    status: text("status").$type<DigestJobStatus>().notNull().default("queued"),
    scheduledFor: timestamp("scheduled_for", { withTimezone: true }).notNull(),
    nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).notNull(),
    attemptCount: integer("attempt_count").notNull().default(0),
    maxAttempts: integer("max_attempts").notNull().default(3),
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }),
    workerId: varchar("worker_id", { length: 96 }),
    sentAt: timestamp("sent_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    lastErrorCode: varchar("last_error_code", { length: 96 }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("idx_digest_jobs_claim").on(
      table.status,
      table.nextAttemptAt,
      table.scheduledFor,
      table.id,
    ),
    index("idx_digest_jobs_user_created").on(table.userId, table.createdAt),
    index("idx_digest_jobs_lease").on(table.status, table.leaseExpiresAt),
    uniqueIndex("digest_jobs_pending_user_channel_unique")
      .on(table.userId, table.channel)
      .where(sql`${table.status} IN ('queued','processing')`),
    check(
      "digest_jobs_channel_check",
      sql`${table.channel} IN ('email','in_app')`,
    ),
    check(
      "digest_jobs_status_check",
      sql`${table.status} IN ('queued','processing','sent','failed','skipped')`,
    ),
    check("digest_jobs_attempt_count_check", sql`${table.attemptCount} >= 0`),
    check("digest_jobs_max_attempts_check", sql`${table.maxAttempts} BETWEEN 1 AND 10`),
    check("digest_jobs_policy_version_check", sql`${table.policyVersion} >= 1`),
  ],
);

export type DigestJob = typeof digestJobs.$inferSelect;

/** Sanitized attempt history for queue operations and aggregate health. */
export const digestAttempts = pgTable(
  "digest_attempts",
  {
    id: serial("id").primaryKey(),
    jobId: integer("job_id")
      .references(() => digestJobs.id, { onDelete: "cascade" })
      .notNull(),
    attemptNumber: integer("attempt_number").notNull(),
    outcome: text("outcome")
      .$type<DigestAttemptOutcome>()
      .notNull()
      .default("started"),
    errorCode: varchar("error_code", { length: 96 }),
    providerMessageId: varchar("provider_message_id", { length: 255 }),
    startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (table) => [
    unique("digest_attempts_job_attempt_unique").on(
      table.jobId,
      table.attemptNumber,
    ),
    index("idx_digest_attempts_job").on(table.jobId),
    index("idx_digest_attempts_outcome_started").on(
      table.outcome,
      table.startedAt,
    ),
    check(
      "digest_attempts_outcome_check",
      sql`${table.outcome} IN ('started','sent','failed','skipped','delivery_unknown')`,
    ),
  ],
);

export type DigestAttempt = typeof digestAttempts.$inferSelect;

/**
 * User Interactions table - Behavioral analytics
 *
 * Tracks all user interactions with resources for analytics and recommendation engine.
 * Enables collaborative filtering and content popularity metrics.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} userId - Reference to the user (required, cascades on delete)
 * @property {number} resourceId - Reference to the interacted resource (required, cascades on delete)
 * @property {string} interactionType - Type of interaction: 'view', 'click', 'bookmark', 'rate', 'complete' (required)
 * @property {number} interactionValue - Quantitative value: rating (1-5) or time spent in seconds
 * @property {object} metadata - Additional interaction data (e.g., referrer, device) (default: empty object)
 * @property {timestamp} timestamp - When the interaction occurred
 *
 * Constraints:
 * - Cascades delete when user or resource is deleted
 *
 * Indexes:
 * - idx_user_interactions_user_id: Analytics queries for user behavior
 * - idx_user_interactions_resource_id: Analytics queries for resource popularity
 * - idx_user_interactions_type: Filter by interaction type
 *
 * Relationships:
 * - References users.id (many-to-one)
 * - References resources.id (many-to-one)
 */
export const userInteractions = pgTable(
  "user_interactions",
  {
    id: serial("id").primaryKey(),
    userId: varchar("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    interactionType: text("interaction_type").notNull(), // view, click, bookmark, rate, complete
    interactionValue: integer("interaction_value"), // rating (1-5) or time spent
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    timestamp: timestamp("timestamp").defaultNow(),
  },
  (table) => [
    index("idx_user_interactions_user_id").on(table.userId),
    index("idx_user_interactions_resource_id").on(table.resourceId),
    index("idx_user_interactions_type").on(table.interactionType),
  ]
);

export const insertUserInteractionSchema = createInsertSchema(userInteractions).pick({
  userId: true,
  resourceId: true,
  interactionType: true,
  interactionValue: true,
  metadata: true,
});

export type InsertUserInteraction = z.infer<typeof insertUserInteractionSchema>;
export type UserInteraction = typeof userInteractions.$inferSelect;

/**
 * GitHub Sync History table - Sync operation tracking
 *
 * Records every GitHub sync operation with detailed statistics and snapshots.
 * Enables version control, rollback, and sync analytics.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} repositoryUrl - GitHub repository URL that was synced (required)
 * @property {string} direction - Sync direction: 'export' (DB → GitHub) or 'import' (GitHub → DB) (required)
 * @property {string} commitSha - Git commit SHA hash
 * @property {string} commitMessage - Git commit message
 * @property {string} commitUrl - Direct URL to the commit on GitHub
 * @property {number} resourcesAdded - Count of resources added in this sync (default: 0)
 * @property {number} resourcesUpdated - Count of resources updated in this sync (default: 0)
 * @property {number} resourcesRemoved - Count of resources removed in this sync (default: 0)
 * @property {number} totalResources - Total resource count after sync (default: 0)
 * @property {string} performedBy - User who initiated the sync (nullable reference)
 * @property {object} snapshot - Complete resource snapshot at time of sync (default: empty object)
 * @property {object} metadata - Additional sync metadata (default: empty object)
 * @property {timestamp} createdAt - When the sync occurred
 *
 * Indexes:
 * - idx_github_sync_history_repo: Track sync history by repository
 * - idx_github_sync_history_direction: Filter by import/export operations
 *
 * Relationships:
 * - References users.id for performedBy (many-to-one, nullable)
 */
export const githubSyncHistory = pgTable(
  "github_sync_history",
  {
    id: serial("id").primaryKey(),
    repositoryUrl: text("repository_url").notNull(),
    direction: text("direction").notNull(), // export, import
    commitSha: text("commit_sha"),
    commitMessage: text("commit_message"),
    commitUrl: text("commit_url"),
    resourcesAdded: integer("resources_added").default(0),
    resourcesUpdated: integer("resources_updated").default(0),
    resourcesRemoved: integer("resources_removed").default(0),
    totalResources: integer("total_resources").default(0),
    performedBy: varchar("performed_by").references(() => users.id),
    snapshot: jsonb("snapshot").$type<Record<string, any>>().default({}), // Resource snapshot
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("idx_github_sync_history_repo").on(table.repositoryUrl),
    index("idx_github_sync_history_direction").on(table.direction),
  ]
);

export const insertGithubSyncHistorySchema = createInsertSchema(githubSyncHistory).pick({
  repositoryUrl: true,
  direction: true,
  commitSha: true,
  commitMessage: true,
  commitUrl: true,
  resourcesAdded: true,
  resourcesUpdated: true,
  resourcesRemoved: true,
  totalResources: true,
  performedBy: true,
  snapshot: true,
  metadata: true,
});

export type InsertGithubSyncHistory = z.infer<typeof insertGithubSyncHistorySchema>;
export type GithubSyncHistory = typeof githubSyncHistory.$inferSelect;

/**
 * Enrichment Jobs table - Batch AI enrichment tracking
 *
 * Manages batch AI enrichment operations that analyze and enhance resource metadata.
 * Tracks progress, success rates, and errors across large-scale enrichment runs.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {string} status - Job status: 'pending', 'processing', 'completed', 'failed', 'cancelled' (default: 'pending')
 * @property {string} filter - Resource filter: 'all' or 'unenriched' (default: 'all')
 * @property {number} batchSize - Number of resources to process per batch (default: 10)
 * @property {number} totalResources - Total resources to enrich (default: 0)
 * @property {number} processedResources - Count of processed resources (default: 0)
 * @property {number} successfulResources - Count of successfully enriched resources (default: 0)
 * @property {number} failedResources - Count of failed enrichments (default: 0)
 * @property {number} skippedResources - Count of skipped resources (default: 0)
 * @property {number[]} processedResourceIds - Array of successfully processed resource IDs (default: empty array)
 * @property {number[]} failedResourceIds - Array of failed resource IDs (default: empty array)
 * @property {string} errorMessage - Error details if job failed
 * @property {object} metadata - Additional job metadata (default: empty object)
 * @property {string} startedBy - User who initiated the enrichment job
 * @property {timestamp} startedAt - When processing began
 * @property {timestamp} completedAt - When job finished (success or failure)
 * @property {timestamp} createdAt - Job creation timestamp
 * @property {timestamp} updatedAt - Last status update timestamp
 *
 * Indexes:
 * - idx_enrichment_jobs_status: Fast filtering by job status
 * - idx_enrichment_jobs_started_by: Track jobs by user
 *
 * Relationships:
 * - References users.id for startedBy (many-to-one, nullable)
 *
 * Referenced by:
 * - enrichmentQueue.jobId (one-to-many)
 */
export const enrichmentJobs = pgTable(
  "enrichment_jobs",
  {
    id: serial("id").primaryKey(),
    status: text("status").notNull().default("pending"), // pending, processing, completed, failed, cancelled
    filter: text("filter").default("all"), // all, unenriched
    batchSize: integer("batch_size").default(10),
    totalResources: integer("total_resources").default(0),
    processedResources: integer("processed_resources").default(0),
    successfulResources: integer("successful_resources").default(0),
    failedResources: integer("failed_resources").default(0),
    skippedResources: integer("skipped_resources").default(0),
    processedResourceIds: jsonb("processed_resource_ids").$type<number[]>().default([]),
    failedResourceIds: jsonb("failed_resource_ids").$type<number[]>().default([]),
    errorMessage: text("error_message"),
    metadata: jsonb("metadata").$type<Record<string, any>>().default({}),
    // Per-run agent config (Claude Agent SDK): model + custom endpoint + encrypted auth token.
    // authTokenEncrypted packs ivHex:tagHex:cipherHex (AES-256-GCM). Null => use platform default (ANTHROPIC_API_KEY).
    model: text("model"),
    baseUrl: text("base_url"),
    authTokenEncrypted: text("auth_token_encrypted"),
    authTokenLast4: text("auth_token_last4"),
    startedBy: varchar("started_by").references(() => users.id),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    index("idx_enrichment_jobs_status").on(table.status),
    index("idx_enrichment_jobs_started_by").on(table.startedBy),
  ]
);

export const insertEnrichmentJobSchema = createInsertSchema(enrichmentJobs).pick({
  filter: true,
  batchSize: true,
  startedBy: true,
  model: true,
  baseUrl: true,
});

export type InsertEnrichmentJob = z.infer<typeof insertEnrichmentJobSchema>;
export type EnrichmentJob = typeof enrichmentJobs.$inferSelect;

/**
 * Enrichment Queue table - Individual resource enrichment tasks
 *
 * Tracks individual resource enrichment tasks within a batch job.
 * Each queue item represents one resource to be analyzed by Claude AI with retry logic.
 *
 * @property {number} id - Auto-incrementing primary key
 * @property {number} jobId - Parent enrichment job (required, cascades on delete)
 * @property {number} resourceId - Resource to enrich (required, cascades on delete)
 * @property {string} status - Task status: 'pending', 'processing', 'completed', 'failed', 'skipped' (default: 'pending')
 * @property {number} retryCount - Number of retry attempts made (default: 0)
 * @property {number} maxRetries - Maximum retry attempts allowed (default: 3)
 * @property {string} errorMessage - Error details if enrichment failed
 * @property {object} aiMetadata - Claude AI-generated metadata (suggested title, description, tags, category, subcategory, confidence, key topics)
 * @property {timestamp} processedAt - When enrichment completed or failed
 * @property {timestamp} createdAt - Queue item creation timestamp
 * @property {timestamp} updatedAt - Last status update timestamp
 *
 * Constraints:
 * - Cascades delete when parent job or resource is deleted
 *
 * Indexes:
 * - idx_enrichment_queue_job_id: Fast lookup of all tasks in a job
 * - idx_enrichment_queue_resource_id: Check enrichment status for a resource
 * - idx_enrichment_queue_status: Fast filtering by task status
 *
 * Relationships:
 * - References enrichmentJobs.id (many-to-one)
 * - References resources.id (many-to-one)
 */
export const enrichmentQueue = pgTable(
  "enrichment_queue",
  {
    id: serial("id").primaryKey(),
    jobId: integer("job_id").references(() => enrichmentJobs.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").references(() => resources.id, { onDelete: "cascade" }).notNull(),
    status: text("status").notNull().default("pending"), // pending, processing, completed, failed, skipped
    retryCount: integer("retry_count").default(0),
    maxRetries: integer("max_retries").default(3),
    errorMessage: text("error_message"),
    aiMetadata: jsonb("ai_metadata").$type<{
      suggestedTitle?: string;
      suggestedDescription?: string;
      suggestedTags?: string[];
      suggestedCategory?: string;
      suggestedSubcategory?: string;
      suggestedSubSubcategory?: string;
      confidence?: number;
      keyTopics?: string[];
    }>(),
    processedAt: timestamp("processed_at"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    index("idx_enrichment_queue_job_id").on(table.jobId),
    index("idx_enrichment_queue_resource_id").on(table.resourceId),
    index("idx_enrichment_queue_status").on(table.status),
  ]
);

export const insertEnrichmentQueueSchema = createInsertSchema(enrichmentQueue).pick({
  jobId: true,
  resourceId: true,
  status: true,
  retryCount: true,
  maxRetries: true,
});

export type InsertEnrichmentQueue = z.infer<typeof insertEnrichmentQueueSchema>;
export type EnrichmentQueueItem = typeof enrichmentQueue.$inferSelect;

export interface LinkHealthJob {
  id: number;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  totalLinks: number;
  checkedLinks: number;
  healthyLinks: number;
  brokenLinks: number;
  redirectLinks: number;
  timeoutLinks: number;
  /** 200-OK responses flagged by takeover/intent-flip/parked heuristics (R4-001/023 class) */
  suspectLinks?: number;
  errorMessage?: string;
  startedAt?: string;
  completedAt?: string;
  createdAt: string;
}

export interface LinkHealthCheck {
  id: number;
  resourceId: number;
  url: string;
  status: 'healthy' | 'broken' | 'timeout' | 'redirect' | 'dns_failure' | 'suspect';
  httpStatus?: number;
  responseTime?: number;
  redirectUrl?: string;
  /** URL after following all redirects (differs from url when the destination moved) */
  finalUrl?: string;
  errorMessage?: string;
  consecutiveFailures: number;
  flaggedForReview: boolean;
  lastCheckedAt: string;
}

// Persisted link-health scan results (survive server restarts/republishes).
// LinkHealthJob/LinkHealthCheck above remain the API wire shape; the service
// maps rows (Date columns) to those interfaces (ISO strings).
export const linkHealthJobs = pgTable(
  "link_health_jobs",
  {
    id: serial("id").primaryKey(),
    status: text("status").notNull().default("pending"),
    totalLinks: integer("total_links").notNull().default(0),
    checkedLinks: integer("checked_links").notNull().default(0),
    healthyLinks: integer("healthy_links").notNull().default(0),
    brokenLinks: integer("broken_links").notNull().default(0),
    redirectLinks: integer("redirect_links").notNull().default(0),
    timeoutLinks: integer("timeout_links").notNull().default(0),
    suspectLinks: integer("suspect_links").notNull().default(0),
    errorMessage: text("error_message"),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("idx_link_health_jobs_status").on(table.status)]
);

export type LinkHealthJobRow = typeof linkHealthJobs.$inferSelect;

export const linkHealthChecks = pgTable(
  "link_health_checks",
  {
    id: serial("id").primaryKey(),
    jobId: integer("job_id").references(() => linkHealthJobs.id, { onDelete: "cascade" }).notNull(),
    resourceId: integer("resource_id").notNull().default(0),
    url: text("url").notNull(),
    status: text("status").notNull(),
    httpStatus: integer("http_status"),
    responseTime: integer("response_time"),
    redirectUrl: text("redirect_url"),
    finalUrl: text("final_url"),
    errorMessage: text("error_message"),
    consecutiveFailures: integer("consecutive_failures").notNull().default(0),
    flaggedForReview: boolean("flagged_for_review").notNull().default(false),
    lastCheckedAt: timestamp("last_checked_at").defaultNow().notNull(),
  },
  (table) => [
    index("idx_link_health_checks_job_id").on(table.jobId),
    index("idx_link_health_checks_status").on(table.status),
  ]
);

export type LinkHealthCheckRow = typeof linkHealthChecks.$inferSelect;

export const researchJobs = pgTable(
  "research_jobs",
  {
    id: serial("id").primaryKey(),
    status: text("status").notNull().default("pending"),
    prompt: text("prompt").notNull(),
    categoryFocus: text("category_focus"),
    maxBudgetUsd: text("max_budget_usd").default("1.00"),
    maxTurns: integer("max_turns").default(30),
    // Per-run agent config (Claude Agent SDK): model + custom endpoint + encrypted auth token.
    // authTokenEncrypted packs ivHex:tagHex:cipherHex (AES-256-GCM). Null => use platform default (ANTHROPIC_API_KEY).
    model: text("model"),
    // Explicit scout (subagent) model override. Null => auto: default scout
    // model on the platform endpoint, or 'inherit' (= orchestrator model)
    // when a custom model/endpoint is configured.
    scoutModel: text("scout_model"),
    // Stop condition: end the run once this many NEW discoveries are saved.
    // Null => no target (run until budget/turns/model decides to stop).
    targetDiscoveries: integer("target_discoveries"),
    baseUrl: text("base_url"),
    authTokenEncrypted: text("auth_token_encrypted"),
    authTokenLast4: text("auth_token_last4"),
    totalDiscoveries: integer("total_discoveries").default(0),
    approvedDiscoveries: integer("approved_discoveries").default(0),
    rejectedDiscoveries: integer("rejected_discoveries").default(0),
    duplicatesSkipped: integer("duplicates_skipped").default(0),
    totalInputTokens: integer("total_input_tokens").default(0),
    totalOutputTokens: integer("total_output_tokens").default(0),
    estimatedCostUsd: text("estimated_cost_usd").default("0.00"),
    turnsUsed: integer("turns_used").default(0),
    agentLog: jsonb("agent_log").$type<Array<{ role: string; content: string; timestamp: string }>>().default([]),
    errorMessage: text("error_message"),
    startedBy: varchar("started_by").references(() => users.id),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("idx_research_jobs_status").on(table.status),
    index("idx_research_jobs_started_by").on(table.startedBy),
  ]
);

export const insertResearchJobSchema = createInsertSchema(researchJobs).pick({
  prompt: true,
  categoryFocus: true,
  maxBudgetUsd: true,
  maxTurns: true,
  startedBy: true,
  model: true,
  baseUrl: true,
});

export type InsertResearchJob = z.infer<typeof insertResearchJobSchema>;
export type ResearchJob = typeof researchJobs.$inferSelect;

/**
 * Async post-save verification payload for a research discovery (July 30, 2026).
 * Written by the fire-and-forget verifier after save_discovery persists —
 * liveness probe via the shared LinkChecker + GitHub repo metadata for
 * github.com URLs. Serves ADMIN REVIEW only (badges in the researcher tab);
 * the model never sees it.
 */
export interface DiscoveryVerification {
  checkedAt: string;
  /** ok = URL answered healthy; dead = probe failed; skipped = URL failed the public-URL guard; unknown = verifier errored. */
  liveness: "ok" | "dead" | "skipped" | "unknown";
  httpStatus?: number;
  finalUrl?: string;
  /** LinkChecker 200-but-gone heuristics (domain-takeover / intent-flip-root / parked-content). */
  suspicion?: string;
  error?: string;
  github?: {
    stars?: number;
    archived?: boolean;
    pushedAt?: string;
    /** GitHub API said no (rate limit / 4xx) — metadata unavailable, not a dead repo. */
    unavailable?: boolean;
  };
}

export const researchDiscoveries = pgTable(
  "research_discoveries",
  {
    id: serial("id").primaryKey(),
    jobId: integer("job_id").references(() => researchJobs.id, { onDelete: "cascade" }).notNull(),
    title: text("title").notNull(),
    url: text("url").notNull(),
    description: text("description"),
    suggestedCategory: text("suggested_category"),
    suggestedSubcategory: text("suggested_subcategory"),
    suggestedSubSubcategory: text("suggested_sub_subcategory"),
    confidence: integer("confidence").default(0),
    reasoning: text("reasoning"),
    status: text("status").notNull().default("pending_review"),
    verification: jsonb("verification").$type<DiscoveryVerification>(),
    approvedAt: timestamp("approved_at"),
    rejectedAt: timestamp("rejected_at"),
    rejectionReason: text("rejection_reason"),
    createdResourceId: integer("created_resource_id").references(() => resources.id),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("idx_research_discoveries_job_id").on(table.jobId),
    index("idx_research_discoveries_status").on(table.status),
    index("idx_research_discoveries_url").on(table.url),
    // Closes the save-retry/flush double-insert race: a timed-out insert that
    // later commits can never coexist with its retry's row.
    uniqueIndex("research_discoveries_job_url_uq").on(table.jobId, table.url),
  ]
);

export const insertResearchDiscoverySchema = createInsertSchema(researchDiscoveries).pick({
  jobId: true,
  title: true,
  url: true,
  description: true,
  suggestedCategory: true,
  suggestedSubcategory: true,
  suggestedSubSubcategory: true,
  confidence: true,
  reasoning: true,
});

export type InsertResearchDiscovery = z.infer<typeof insertResearchDiscoverySchema>;
export type ResearchDiscovery = typeof researchDiscoveries.$inferSelect;

/**
 * Agent Events table - Structured, persisted log of the Claude Agent SDK multi-agent runs.
 *
 * Polymorphic across both agent flows: (jobType, jobId) identifies the parent run
 * (jobType 'research' -> research_jobs.id, 'enrichment' -> enrichment_jobs.id).
 * Rows are appended in stream order (seq) as SDKMessages arrive from query(), and feed
 * both the admin log viewer and the multi-agent communication graph.
 *
 * eventType: 'lifecycle' | 'message' | 'thinking' | 'tool_call' | 'tool_result'
 *          | 'delegation' | 'delegation_result' | 'result' | 'error'
 * actorType: 'orchestrator' | 'subagent' | 'tool' | 'system'
 * For delegation edges, targetActor names the subagent being spawned/messaged.
 */
export const agentEvents = pgTable(
  "agent_events",
  {
    id: serial("id").primaryKey(),
    jobType: text("job_type").notNull(), // 'research' | 'enrichment'
    jobId: integer("job_id").notNull(),
    seq: integer("seq").notNull(),
    actor: text("actor").notNull(),
    actorType: text("actor_type").notNull(),
    eventType: text("event_type").notNull(),
    model: text("model"),
    targetActor: text("target_actor"),
    summary: text("summary"),
    detail: jsonb("detail").$type<Record<string, any>>().default({}),
    tokensIn: integer("tokens_in"),
    tokensOut: integer("tokens_out"),
    costUsd: text("cost_usd"),
    durationMs: integer("duration_ms"),
    ts: timestamp("ts").defaultNow(),
  },
  (table) => [
    index("idx_agent_events_job").on(table.jobType, table.jobId),
    index("idx_agent_events_job_seq").on(table.jobType, table.jobId, table.seq),
  ]
);

/**
 * Rate limit hit counters (Task #279) — shared fixed-window store for every
 * express-rate-limit instance in the app. The default in-memory store is
 * per-process, so under Autoscale fan-out the advertised per-IP limits were
 * effectively multiplied by the instance count. Counters here are keyed by
 * (limiter name, client key) so all instances share ONE budget and the
 * RateLimit-* headers stay accurate regardless of which instance answers.
 * Mirrors migrations/0039_rate_limit_hits.sql.
 */
export const rateLimitHits = pgTable(
  "rate_limit_hits",
  {
    limiter: varchar("limiter", { length: 64 }).notNull(),
    key: varchar("key", { length: 256 }).notNull(),
    hits: integer("hits").notNull().default(0),
    resetAt: timestamp("reset_at", { withTimezone: true }).notNull(),
  },
  (table) => ({
    pk: primaryKey({ name: "rate_limit_hits_pk", columns: [table.limiter, table.key] }),
    resetAtIdx: index("idx_rate_limit_hits_reset_at").on(table.resetAt),
  })
);

export const insertAgentEventSchema = createInsertSchema(agentEvents).omit({
  id: true,
  ts: true,
});

export type InsertAgentEvent = z.infer<typeof insertAgentEventSchema>;
export type AgentEvent = typeof agentEvents.$inferSelect;

// Whitelist of fields editable via user-submitted resource edits.
// Shared between routes.ts (sanitize incoming edits) and AuditRepository.ts (apply merged edits).
export const EDITABLE_RESOURCE_FIELDS = [
  'title',
  'description',
  'url',
  'tags',
  'category',
  'subcategory',
  'subSubcategory',
  'resourceFormat',
  'provider',
  'skillLevel',
] as const;
export type EditableResourceField = typeof EDITABLE_RESOURCE_FIELDS[number];
