import React, { useState } from "react";
import "./_group.css";

export function ComponentsPatterns() {
 const [saved,setSaved]=useState(false); const [tab,setTab]=useState("Overview");
 return <main className="avds"><div className="avds-shell"><Top/><header className="avds-hero"><div><div className="avds-kicker">02 / Components & patterns</div><h1>Stable parts. <em>Legible</em> behavior.</h1><p className="avds-lead">Components own their labels, keyboard behavior, states, and minimum targets. Personalities may change the finish; they do not rewrite the contract.</p></div><Meta/></header>
 <section className="avds-section"><Head title="Interaction states" text="The component state is explicit, not implied by color. Every control reaches a 40 × 40 CSS pixel target and has a visible active-accent focus ring."/><div className="avds-grid cols-3"><article className="avds-card"><h3>Actions</h3><div className="avds-buttonrow"><button className="avds-btn primary" onClick={()=>setSaved(!saved)}>{saved?"Saved resource":"Save resource"}</button><button className="avds-btn">Secondary</button><button className="avds-btn" disabled>Unavailable</button></div><p className="avds-state">{saved?"Selected / persistent confirmation":"Default / hover / disabled"}</p></article><article className="avds-card"><h3>Field anatomy</h3><label className="avds-state" htmlFor="resource-note">Private annotation</label><input id="resource-note" className="avds-input" placeholder="Add an operational note" /><p className="avds-state">Label remains visible · error adds copy</p></article><article className="avds-card"><h3>Status semantics</h3><div className="avds-buttonrow"><span className="avds-status ok">Healthy · 18</span><span className="avds-status warn">Review · 3</span><span className="avds-status bad">Blocked · 1</span></div><p className="avds-state">Text + border + accessible name</p></article></div></section>
 <section className="avds-section"><Head title="Component anatomy" text="The API names the job a part performs. Component roles consume semantic tokens, never primitive color or spacing values."/><table className="avds-table"><thead><tr><th>Component</th><th>Anatomy</th><th>Required behavior</th><th>Token roles</th></tr></thead><tbody><tr><td>Button</td><td>label · optional icon · state</td><td>40px target, keyboard activation, disabled semantics</td><td className="avds-token">accent / surface / border</td></tr><tr><td>Field</td><td>label · control · help · error</td><td>Programmatic label, focus, error announced</td><td className="avds-token">surface / ink / border</td></tr><tr><td>Notice</td><td>status · concise message · action</td><td>Color supplemented by copy and icon label</td><td className="avds-token">status / surface / ink</td></tr><tr><td>Resource row</td><td>title · metadata · save action</td><td>Reading order survives compact layout</td><td className="avds-token">surface / hairline / accent</td></tr></tbody></table></section>
 <section className="avds-section"><Head title="Pattern: resource review" text="A responsive composition keeps the decision and relevant evidence together. Below tablet, the rail moves before the content and no control disappears."/><div className="avds-pattern"><aside className="avds-pattern-rail"><b>FILTER / 04</b>Codec<br/>Delivery<br/>Rights<br/>Saved</aside><div className="avds-pattern-main"><div className="avds-buttonrow" role="tablist" aria-label="Resource sections">{["Overview","Notes","History"].map(t=><button key={t} className={"avds-btn "+(tab===t?"primary":"")} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div><div role="tabpanel" style={{marginTop:14}}>{tab==="Overview"?<><div className="avds-listitem"><span><strong>AV1 encoding for constrained delivery</strong><small>Guide · 12 min read · Updated 8 days ago</small></span><span className="avds-status ok">Verified</span></div><div className="avds-listitem"><span><strong>Color-managed review stations</strong><small>Checklist · 7 controls · Owner: Post team</small></span><span className="avds-status warn">Review</span></div></>:<p style={{color:"var(--muted)",fontSize:13}}>The {tab.toLowerCase()} pane preserves its own task-specific pattern without changing the resource row contract.</p>}</div></div></div></section>
 <section className="avds-section"><Head title="Responsive contracts" text="Patterns adapt composition, not meaning. Keep order, names, focus, and status semantics when chrome changes."/><div className="avds-grid cols-3"><article className="avds-card"><h3>Wide</h3><p>Rail + content. Evidence and action remain visible.</p></article><article className="avds-card"><h3>Medium</h3><p>Rail condenses into an exposed filter control; action stays beside title.</p></article><article className="avds-card"><h3>Compact</h3><p>Single reading column. Metadata wraps before title truncates.</p></article></div></section><Footer/></div></main>
}
function Top(){return <nav className="avds-top" aria-label="Design system sections"><div className="avds-mark"><i/>Awesome.Video / system manual</div><div className="avds-topnav"><span>Foundations</span><span aria-current="page">Components</span><span>Integration</span></div></nav>}
function Meta(){return <aside className="avds-meta"><div><b>Reference</b><span>DS / COMPONENTS</span></div><div><b>Scope</b><span>Shared UI contract</span></div><div><b>Release</b><span>v1.0.0</span></div></aside>}
function Head(p:{title:string;text:string}){return <div className="avds-sectionhead"><h2>{p.title}</h2><p>{p.text}</p></div>}
function Footer(){return <footer className="avds-footer"><span>Awesome.Video federated system</span><span>Component behavior is shared</span></footer>}