import React from "react";
import "./_group.css";

// DS-OK: reference swatches deliberately display the governed Awesome.Video token values.
const colors = [["Page / --bg","#000000"],["Raised / --bg-2","#070706"],["Primary ink / --text","#f4f3ee"],["Secondary / --text-2","rgba(244,243,238,.66)"],["Crimson / --accent","#ff3d52"],["Violet / --accent-2","#b84dff"],["Healthy / status.ok","#34d08c"],["Attention / status.warn","#ffb84d"]];
export function Foundations() {
 return <main className="avds"><div className="avds-shell">
  <Top active="Foundations"/><header className="avds-hero avds-reveal"><div><div className="avds-kicker">01 / Shared foundations</div><h1>The common <em>material</em> of every surface.</h1><p className="avds-lead">Foundations are the stable visual and behavioral layer beneath five system personalities. They describe intent, not decoration, so a learning workspace and a printed field guide can speak with one exact voice.</p></div><Meta code="DS / FOUNDATION" scope="All product surfaces" version="v1.0.0"/></header>
  <section className="avds-section"><Head title="Token direction" text="Values only travel downstream. A product can select a personality and compose a pattern; it cannot mint a new raw value."/><div className="avds-flow"><div><strong>01 / Primitive</strong><p>Reference values, held in source only.</p></div><div className="arrow">→</div><div><strong>02 / Semantic</strong><p>Intent: surface, ink, border, accent.</p></div><div className="arrow">→</div><div><strong>03 / Component</strong><p>Stable roles: button, field, notice.</p></div><div className="arrow">→</div><div><strong>04 / Pattern</strong><p>Product composition and density.</p></div></div></section>
  <section className="avds-section"><Head title="Color roles" text="Editorial + Crimson is the reference expression. Surfaces remain dark paper; annotation ink is reserved for direction, selection, and consequence."/><div className="avds-grid cols-4">{colors.map(([n,c])=><article className="avds-card avds-reveal" key={n}><div className="avds-swatch" style={{background:c}}/><h3>{n}</h3><span className="avds-token">{c}</span></article>)}</div><div className="avds-callout" style={{marginTop:16}}><strong>Contrast rule.</strong> Primary ink is for headings, secondary ink for reading, tertiary ink only for metadata. Color never carries state alone.</div></section>
  <section className="avds-section"><Head title="Typography" text="Fraunces carries editorial emphasis. Manrope makes long technical prose calm. DM Mono marks coordinates, code, and operational facts."/><div className="avds-grid cols-3"><article className="avds-card"><div className="avds-type-display">Frame by frame.</div><div className="avds-rule"/><span className="avds-token">--font-display · Fraunces 500</span></article><article className="avds-card"><div className="avds-type-body">A shared language should disappear while someone is trying to solve a difficult production problem.</div><div className="avds-rule"/><span className="avds-token">--font-body · Manrope 400</span></article><article className="avds-card"><div className="avds-type-mono">BITRATE / 38.4 MBPS<br/>PROFILE / HIGH 10</div><div className="avds-rule"/><span className="avds-token">--font-mono · DM Mono 400</span></article></div><div className="avds-card" style={{marginTop:12}}>{[["display / 64","1.04 leading · -0.02em"],["heading / 20","1.2 leading · semibold"],["body / 15","1.6 leading · secondary ink"],["metadata / 11","mono · 0.12em tracking"]].map(x=><div className="avds-scale" key={x[0]}><span>{x[0]}</span><span>{x[1]}</span></div>)}</div></section>
  <section className="avds-section"><Head title="Space, grid & motion" text="A four-pixel rhythm holds the density. Motion confirms cause and effect; it must never compete with the technical content."/><div className="avds-grid cols-3"><article className="avds-card"><h3>Spacing</h3><p className="avds-token">4 · 8 · 12 · 16 · 24 · 32 · 48 · 64</p><div className="avds-rule"/><p>Use 24 for component breathing room; 48 or 64 to begin a new idea.</p></article><article className="avds-card"><h3>Grid</h3><p className="avds-token">12 columns · 24 gutter · max 1200</p><div className="avds-rule"/><p>Collapse to a single reading column below 720px. The sidebar is optional, never required for task completion.</p></article><article className="avds-card"><h3>Motion</h3><p className="avds-token">160ms · 240ms · 400ms</p><div className="avds-rule"/><p>Transform and opacity only. Respect reduced-motion preferences by removing non-essential movement.</p></article></div></section>
  <Footer/></div></main>
}
function Top({active}:{active:string}){return <nav className="avds-top" aria-label="Design system sections"><div className="avds-mark"><i/>Awesome.Video / system manual</div><div className="avds-topnav">{["Foundations","Components","Integration"].map(x=><span key={x} aria-current={x===active?"page":undefined}>{x}</span>)}</div></nav>}
function Meta(p:{code:string;scope:string;version:string}){return <aside className="avds-meta"><div><b>Reference</b><span>{p.code}</span></div><div><b>Scope</b><span>{p.scope}</span></div><div><b>Release</b><span>{p.version}</span></div></aside>}
function Head(p:{title:string;text:string}){return <div className="avds-sectionhead"><h2>{p.title}</h2><p>{p.text}</p></div>}
function Footer(){return <footer className="avds-footer"><span>Awesome.Video federated system</span><span>Internal standard / maintained by foundations</span></footer>}