import React from "react";
import "./_group.css";

const profiles=[["Public discovery","Editorial + Crimson","Comfortable","Editorial hierarchy, discovery composition"],["Learning workspace","Geist + Cyan","Balanced","Progress, saved state, focused tasks"],["Admin operations","Swiss + Orange","Dense","Tables, bulk action, audit status"],["Standalone exports","Editorial + Crimson","Document","Pagination and print composition"],["Embedded integrations","Host-neutral + inherited","Compact","Container adaptation, reduced chrome"]];
export function IntegrationGovernance(){return <main className="avds"><div className="avds-shell"><Top/><header className="avds-hero"><div><div className="avds-kicker">03 / Product integration & governance</div><h1>Many products. <em>One</em> accountable system.</h1><p className="avds-lead">Federation grants products a recognizable local expression without letting accessibility, semantic intent, or foundational values drift apart.</p></div><Meta/></header>
<section className="avds-section"><Head title="Product profiles" text="Profiles are useful defaults, not separate systems. All profiles keep shared component APIs, status colors, target sizes, and motion preferences."/><table className="avds-table"><thead><tr><th>Profile</th><th>Default expression</th><th>Density</th><th>Local ownership</th></tr></thead><tbody>{profiles.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={v} className={i===1?"avds-token":undefined}>{v}</td>)}</tr>)}</tbody></table></section>
<section className="avds-section"><Head title="Adoption path" text="There is no big-bang rewrite. Products stay shippable while they migrate from foundations through components into documented compositions."/><div className="avds-grid cols-3"><div className="avds-card"><Step n="01" title="Inventory" text="Map raw values and local primitives to existing semantic roles and contracts."/><Step n="02" title="Assign profile" text="Choose the default personality, accent, density, and composition layer."/></div><div className="avds-card"><Step n="03" title="Replace values" text="Move raw colors, fonts, radii, and motion to shared semantic tokens."/><Step n="04" title="Replace primitives" text="Adopt shared components before rebuilding page-level compositions."/></div><div className="avds-card"><Step n="05" title="Migrate patterns" text="Use documented task patterns; record a gap rather than fork a component."/><Step n="06" title="Enable gates" text="Remove temporary exceptions and enforce relevant drift checks."/></div></div></section>
<section className="avds-section"><Head title="Ownership boundaries" text="A clear decision path keeps the system responsive to product work without turning every local need into an unreviewed foundation change."/><div className="avds-grid cols-3"><article className="avds-card"><span className="avds-token">FOUNDATION OWNERS</span><h3>Approve semantics</h3><p>Color roles, type roles, motion, minimum targets, and accessibility changes.</p></article><article className="avds-card"><span className="avds-token">COMPONENT OWNERS</span><h3>Maintain contracts</h3><p>Anatomy, state coverage, keyboard behavior, and implementation guidance.</p></article><article className="avds-card"><span className="avds-token">PRODUCT OWNERS</span><h3>Compose responsibly</h3><p>Patterns, profile selection, and proposals for capabilities the system lacks.</p></article></div></section>
<section className="avds-section"><Head title="Naming & release policy" text="Names describe purpose. Releases make the cost of change visible before a product gets surprised."/><div className="avds-grid cols-3"><article className="avds-card"><h3>Token naming</h3><p className="avds-token">--surface / --text-2 / --accent<br/>--motion-base / --radius-sm</p><div className="avds-rule"/><p>Use role names, never a hue or arbitrary measurement in consumer code.</p></article><article className="avds-card"><h3>Component naming</h3><p className="avds-token">button.primary<br/>resource-row.saved<br/>notice.warning</p><div className="avds-rule"/><p>Stable noun + role/state. Do not expose system personality in the API.</p></article><article className="avds-card"><h3>Versions</h3><p><b>Major</b> breaking token or component changes.<br/><b>Minor</b> additive capability.<br/><b>Patch</b> fix-only.</p><div className="avds-rule"/><p>Every major includes a migration note and compatibility window.</p></article></div></section>
<section className="avds-section"><Head title="Release gates" text="Automation protects the visible agreement. A release does not pass because it looks close; it passes when its contracts remain intact."/><div className="avds-callout"><strong>Required checks:</strong> palette registry · accent registry · theme types · button standards · standalone artifacts · dead exports/components. Add a gate when a class of drift appears twice.</div></section><Footer/></div></main>}
function Step(p:{n:string;title:string;text:string}){return <div className="avds-step"><b>{p.n}</b><div><h3>{p.title}</h3><p>{p.text}</p></div></div>}
function Top(){return <nav className="avds-top" aria-label="Design system sections"><div className="avds-mark"><i/>Awesome.Video / system manual</div><div className="avds-topnav"><span>Foundations</span><span>Components</span><span aria-current="page">Integration</span></div></nav>}
function Meta(){return <aside className="avds-meta"><div><b>Reference</b><span>DS / GOVERNANCE</span></div><div><b>Scope</b><span>All product teams</span></div><div><b>Release</b><span>v1.0.0</span></div></aside>}
function Head(p:{title:string;text:string}){return <div className="avds-sectionhead"><h2>{p.title}</h2><p>{p.text}</p></div>}
function Footer(){return <footer className="avds-footer"><span>Awesome.Video federated system</span><span>Governance makes consistency durable</span></footer>}