name: Build React Assets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-react:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2 hours for complete build
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Fetch awesome-video data
      run: |
        npx tsx scripts/build-static.ts
        
    - name: Build React application
      timeout-minutes: 90
      run: |
        export NODE_OPTIONS="--max-old-space-size=16384"
        export NODE_ENV=production
        export VITE_STATIC_BUILD=true
        export VITE_GA_MEASUREMENT_ID=G-383541848
        export VITE_SITE_TITLE="Awesome Video Dashboard" 
        export VITE_SITE_DESCRIPTION="A curated collection of awesome video resources and tools"
        export VITE_SITE_URL="https://krzemienski.github.io/awesome-list-site"
        export VITE_DEFAULT_THEME="red"
        
        echo "Starting optimized Vite build..."
        # Build with chunking and optimizations
        npx vite build --mode production --target es2020 --chunkSizeWarningLimit 2000
        
    - name: Verify build output
      run: |
        if [ ! -f "dist/public/index.html" ]; then
          echo "❌ Build failed - index.html not found"
          exit 1
        fi
        
        echo "✅ Build verification successful"
        ls -la dist/public/
        
    - name: Commit build to deployment branch
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Create/switch to deployment branch
        git checkout -B gh-pages-build
        
        # Remove everything except dist and .git
        find . -maxdepth 1 ! -name 'dist' ! -name '.git' ! -name '.' -exec rm -rf {} +
        
        # Move dist contents to root
        mv dist/public/* .
        rmdir dist/public
        rmdir dist
        
        # Add all files
        git add -A
        
        # Commit if there are changes
        if ! git diff --staged --quiet; then
          git commit -m "Build React assets for deployment [$(date)]"
          git push -f origin gh-pages-build
          echo "✅ Pushed built assets to gh-pages-build branch"
        else
          echo "ℹ️ No changes to commit"
        fi